#!/usr/bin/env python3
"""Add CONTENT entries for 9 missing domains (43 topics) to enrich_content.py
and regenerate knowledge files.
"""
import sys, re
from pathlib import Path

BASE = Path("C:/Users/made1/alive-engineering-standard")
ENRICH_FILE = BASE / "scripts" / "enrich_content.py"

# ── Content for all 9 missing domains ──

ANALYTICS = {
    'analytics/doc-1/': {
        'title': '数据分析规范',
        'overview': '数据分析是数据驱动决策的核心环节。本规范定义了数据分析的流程标准、工具选型、报告格式和质量要求，确保分析结果的准确性、可追溯性和可复现性。',
        'principles': ['数据驱动：所有决策必须基于数据，避免主观臆断', '可复现：分析过程和结果必须能被他人完整复现', '可视化优先：复杂数据通过可视化图表呈现，降低理解门槛', '业务对齐：分析指标必须与业务目标直接关联'],
        'rules': [
            ('ANL-001', '每次分析必须明确：分析目标、数据来源、分析方法、预期产出', 'P0', '是'),
            ('ANL-002', '分析报告必须包含：摘要、数据说明、分析方法、结果、结论与建议', 'P0', '是'),
            ('ANL-003', '数据清洗过程必须记录去除的数据量、原因和过滤条件', 'P0', '是'),
            ('ANL-004', '统计分析必须注明置信区间和显著性水平', 'P1', '推荐'),
            ('ANL-005', '分析结果必须经过至少一人交叉验证', 'P1', '推荐'),
        ],
        'faqs': [
            ('分析报告的最小结构要求？', '必须包含：摘要（Executive Summary）、数据说明（数据源、时间范围、样本量）、分析方法、分析结果（含可视化）、结论与行动建议。'),
            ('如何保证分析结果可靠？', '① 数据验证（源数据校验）② 方法验证（合理性检查）③ 结果验证（交叉验证）④ 敏感性分析（关键假设变化的影响）。'),
        ],
        'checks': [
            '分析目标与业务目标对齐',
            '数据来源明确可追溯',
            '清洗过程完整记录',
            '统计方法合理',
            '结果经过交叉验证',
            '报告结构完整',
        ],
        'prompt_sp': '你是一个资深数据分析专家，精通统计学、数据可视化和业务分析。',
        'prompt_up': '请对以下数据进行分析：\n数据描述：{data_description}\n分析目标：{analysis_goal}\n业务背景：{business_context}',
        'example_text': "```python\n# 数据分析示例：用户留存分析\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\n# 1. 数据加载\nuser_activity = pd.read_csv('user_activity.csv')\nprint(f'数据范围: {user_activity[\"date\"].min()} ~ {user_activity[\"date\"].max()}')\nprint(f'用户总量: {user_activity[\"user_id\"].nunique()}')\n\n# 2. 留存率计算\ndef cohort_retention(df, period=7):\n    cohort_data = df.groupby('cohort_date')['user_id'].nunique()\n    retention = {}\n    for date in cohort_data.index[:10]:\n        base_users = df[df['cohort_date'] == date]['user_id'].nunique()\n        retained = df[(df['cohort_date'] == date) & (df['days_since_signup'] >= period)]['user_id'].nunique()\n        retention[date] = retained / base_users\n    return pd.Series(retention)\n\nretention_7d = cohort_retention(user_activity, 7)\nprint(f'7日留存率: {retention_7d.mean():.1%}')\n\n# 3. 可视化\nplt.figure(figsize=(12, 6))\nretention_7d.plot(marker='o')\nplt.title('7日留存率趋势')\nplt.xlabel('注册日期')\nplt.ylabel('留存率')\nplt.grid(True, alpha=0.3)\nplt.savefig('retention_trend.png', dpi=150)\n```",
        'example_ext': 'py',
    },
    'analytics/doc-2/': {
        'title': '事件追踪标准',
        'overview': '事件追踪是理解用户行为和产品表现的基础设施。本规范定义了事件命名规则、属性结构、触发时机和数据质量标准，确保跨团队协作的数据一致性。',
        'principles': ['统一规范：事件命名和属性结构全局统一', '语义清晰：事件名能直观表达用户行为', '完整覆盖：关键用户路径必须全量埋点', '质量可控：事件数据必须经过质量校验'],
        'rules': [
            ('ANL-EVT-001', '事件名采用 对象:动作 格式（如 user:login, order:create）', 'P0', '是'),
            ('ANL-EVT-002', '每个事件必须包含：event_id、user_id、timestamp、device_id', 'P0', '是'),
            ('ANL-EVT-003', '所有事件的属性结构必须预定义并版本化管理', 'P0', '是'),
            ('ANL-EVT-004', '关键漏斗事件（注册/下单/支付）必须全量采集', 'P0', '是'),
            ('ANL-EVT-005', '事件数据延迟超过 1 小时的数据需标记为延迟数据', 'P1', '推荐'),
        ],
        'faqs': [
            ('事件和页面浏览的区别？', '事件（Event）描述用户的主动行为（点击、滑动、提交）。页面浏览（PageView）描述页面访问。事件可以有属性（属性值），页面浏览通常只有路径和来源。'),
            ('什么时候用客户端埋点 vs 服务端埋点？', '客户端埋点：前端交互行为、UI 元素点击、页面浏览。服务端埋点：业务关键操作、下单支付、数据变更。关键业务事件建议双端埋点互相校验。'),
        ],
        'checks': [
            '事件名符合 对象:动作 格式',
            '必填属性完整',
            '事件属性已预定义',
            '关键事件已全量埋点',
            '埋点已通过 QA 验收',
            '事件文档已更新',
        ],
        'prompt_sp': '你是一个事件追踪架构师，精通用户行为分析和埋点设计。',
        'prompt_up': '请为以下产品功能设计事件追踪方案：\n功能描述：{feature_description}\n用户路径：{user_journey}\n关键指标：{key_metrics}',
        'example_text': "```yaml\n# 事件追踪方案示例：电商下单流程\n# 事件定义\nevents:\n  - name: order:create\n    description: 用户创建订单\n    trigger: 点击「提交订单」按钮\n    properties:\n      - order_id: string       # 订单号\n      - total_amount: float    # 订单金额\n      - item_count: int        # 商品数量\n      - coupon_id: string?     # 使用的优惠券（可选）\n      - payment_method: string # 支付方式\n    \n  - name: order:pay\n    description: 用户完成支付\n    trigger: 支付成功回调\n    properties:\n      - order_id: string\n      - pay_amount: float\n      - pay_channel: string    # 微信/支付宝/银行卡\n      - pay_duration: int      # 支付耗时（秒）\n\n# 用户路径（漏斗）\nfunnel:\n  - name: checkout_funnel\n    steps:\n      - event: cart:view\n      - event: order:create\n      - event: order:pay\n    \n# 核心指标\nmetrics:\n  - name: cart_to_order_rate\n    formula: order:create / cart:view\n  - name: payment_success_rate\n    formula: order:pay / order:create\n```",
        'example_ext': 'yaml',
    },
    'analytics/doc-3/': {
        'title': '指标定义规范',
        'overview': '统一的指标定义是数据驱动的基础。本规范规定了指标的命名、计算方式、数据口径和业务含义的标准格式，确保全公司对同一指标的理解一致。',
        'principles': ['唯一来源：每个指标只有一个官方定义', '口径统一：同一指标在不同场景的计算逻辑必须一致', '可度量：指标必须有明确的量纲和计算方式', '可追溯：指标的变更历史必须有记录'],
        'rules': [
            ('ANL-MET-001', '指标命名采用 业务域_指标名 格式（如 order_gmv, user_retention_7d）', 'P0', '是'),
            ('ANL-MET-002', '每个指标必须明确：口径说明、计算逻辑、数据源、更新频率', 'P0', '是'),
            ('ANL-MET-003', '指标变更必须通过评审，更新版本号并通知所有消费者', 'P0', '是'),
            ('ANL-MET-004', '比率类指标必须注明分子和分母的口径', 'P0', '是'),
            ('ANL-MET-005', '指标看板必须标注数据延迟时间', 'P1', '推荐'),
        ],
        'faqs': [
            ('指标口径不一致的典型问题？', '最常见的是 GMV 定义差异：包含取消订单 vs 不包含、含税 vs 不含税、包含运费 vs 不包含。解决方案是通过指标字典统一口径，每个指标标明含/排除规则。'),
            ('如何管理指标变更？', '指标变更步骤：① 提出变更申请 ② 评估影响范围（哪些报表/看板受影响）③ 评审通过后更新指标字典 ④ 同时运行新旧口径 1-2 个周期确保一致性 ⑤ 通知所有消费者迁移。'),
        ],
        'checks': [
            '指标命名符合规范',
            '计算逻辑明确易懂',
            '数据源和口径已定义',
            '更新频率已标注',
            '指标字典已同步',
            '变更流程已执行',
        ],
        'prompt_sp': '你是一个数据治理专家，精通指标管理体系的设计和落地。',
        'prompt_up': '请为以下业务场景设计指标体系：\n业务领域：{business_domain}\n核心目标：{core_objectives}\n利益相关方：{stakeholders}',
        'example_text': "```yaml\n# 指标定义示例：电商业务\nmetrics:\n  # 交易类指标\n  - name: order_gmv\n    display_name: 商品交易总额\n    definition: 用户支付成功的订单金额总和（含税含运费）\n    formula: SUM(order.pay_amount) WHERE order.status = 'paid'\n    data_source: order_payment_table\n    frequency: T+1实时\n    unit: 元\n    owner: 电商数据组\n    \n  - name: order_avg_price\n    display_name: 客单价\n    definition: 单笔订单的平均支付金额\n    formula: SUM(pay_amount) / COUNT(DISTINCT order_id)\n    data_source: order_payment_table\n    frequency: T+1\n    unit: 元\n\n  # 用户类指标\n  - name: user_retention_7d\n    display_name: 7日留存率\n    definition: 当日新增用户中，7日后仍有活跃行为的比例\n    formula: |\n      retained_users(N day 0 cohort) /\n      new_users(N day 0) \n      WHERE active_in_day >= 7\n    data_source: user_activity_table\n    frequency: T+1\n    unit: '%'\n\n  # 质量类指标\n  - name: order_refund_rate\n    display_name: 退款率\n    definition: 发起退款的订单占总支付订单的比例\n    formula: COUNT(refund_order_id) / COUNT(pay_order_id)\n    data_source: refund_table / order_table\n    frequency: T+1\n    unit: '%'\n```",
        'example_ext': 'yaml',
    },
    'analytics/doc-4/': {
        'title': '数据可视化标准',
        'overview': '数据可视化是将分析结果直观呈现的关键手段。本规范定义了图表选择标准、设计原则、交互规范和看板布局规则，确保数据传达的准确性和高效性。',
        'principles': ['图表选对：数据关系决定图表类型', '简洁清晰：去除非必要的装饰元素', '色彩语义：颜色有明确的信息层级含义', '移动优先：看板需适配不同屏幕尺寸'],
        'rules': [
            ('ANL-VIZ-001', '趋势数据使用折线图，对比数据使用柱状图，占比数据使用饼图/环形图', 'P0', '是'),
            ('ANL-VIZ-002', '颜色使用不超过 7 种，且需考虑色盲友好（避免红绿搭配）', 'P0', '是'),
            ('ANL-VIZ-003', '图表必须标注坐标轴说明、数据单位和数据更新时间', 'P0', '是'),
            ('ANL-VIZ-004', '指标卡必须显示：当前值、变化趋势、变化百分比、对比基准', 'P0', '是'),
            ('ANL-VIZ-005', '看板加载时间不得超过 3 秒，大数据量需预聚合', 'P1', '推荐'),
        ],
        'faqs': [
            ('看板设计的最佳实践？', '① 最重要的指标放在左上角（用户视线自然起点）② 关联指标放在一起 ③ 使用一致的色彩体系（绿色=好，红色=差，灰色=基准）④ 提供 drill-down 交互 ⑤ 定期收集用户反馈迭代。'),
            ('数据太多怎么展示？', '分层策略：概览层（3-5 个核心指标）→ 分析层（10-15 个细分指标）→ 明细层（可下钻查看原始数据）。提供筛选器和日期范围选择器。'),
        ],
        'checks': [
            '图表类型匹配数据关系',
            '色彩使用不超过 7 种',
            '坐标轴和数据单位已标注',
            '色盲友好验证通过',
            '看板加载性能达标',
            '移动端适配检查',
        ],
        'prompt_sp': '你是一个数据可视化专家，精通 BI 看板设计和信息传达。',
        'prompt_up': '请为以下指标设计可视化看板：\n核心指标：{key_metrics}\n使用场景：{usage_scenario}\n用户角色：{user_roles}',
        'example_text': "```typescript\n// 数据看板组件示例：核心指标卡\nimport { Card, Trend, Sparkline } from '@ant-design/charts';\n\ninterface MetricCardProps {\n  title: string;\n  value: number;\n  unit: string;\n  trend: 'up' | 'down' | 'flat';\n  changePercent: number;\n  sparklineData: number[];\n  baseline: string;\n}\n\nexport const MetricCard: React.FC<MetricCardProps> = ({\n  title, value, unit, trend, changePercent, sparklineData, baseline\n}) => {\n  const colorMap = { up: '#52c41a', down: '#ff4d4f', flat: '#faad14' };\n  \n  return (\n    <Card className=\"metric-card\" hoverable>\n      <div className=\"metric-title\">{title}</div>\n      <div className=\"metric-value\" style={{ color: colorMap[trend] }}>\n        {value.toLocaleString()}<span className=\"metric-unit\">{unit}</span>\n      </div>\n      <div className=\"metric-trend\">\n        <Trend type={trend} />\n        <span className=\"change\" style={{ color: colorMap[trend] }}>\n          {changePercent > 0 ? '+' : ''}{changePercent}%\n        </span>\n        <span className=\"baseline\">vs {baseline}</span>\n      </div>\n      <Sparkline data={sparklineData} height={40} width={200} />\n    </Card>\n  );\n};\n```",
        'example_ext': 'tsx',
    },
    'analytics/a-b/': {
        'title': 'A/B 测试规范',
        'overview': 'A/B 测试是产品迭代中验证假设的金标准。本规范覆盖实验设计、流量分配、样本量计算、统计分析和决策标准，确保实验结论的科学性和可靠性。',
        'principles': ['单变量原则：每次实验只测试一个变量', '随机化：用户分流必须随机且不可穿透', '充分样本量：实验必须运行到统计显著为止', '先验假设：实验开始前必须明确假设和成功指标'],
        'rules': [
            ('ANL-AB-001', 'A/B 测试必须提前定义：实验假设、核心指标、最小 detectable effect', 'P0', '是'),
            ('ANL-AB-002', '分流必须基于 user_id 哈希，确保用户在不同实验间的一致性', 'P0', '是'),
            ('ANL-AB-003', '实验最小运行周期为 7 天，覆盖完整的周周期效应', 'P0', '是'),
            ('ANL-AB-004', '统计显著性水平设为 95%（p < 0.05），严禁提前停止实验', 'P0', '是'),
            ('ANL-AB-005', '同时运行的互斥实验不能超过 3 个，避免流量竞争', 'P1', '推荐'),
        ],
        'faqs': [
            ('实验多久能出结果？', '取决于：① 样本量（日均流量）② Minimum Detectable Effect（MDE，期望的最小改善幅度）③ 基线转化率。通常建议至少运行 7 天（覆盖工作日/周末差异）。使用样本量计算器提前估算。'),
            ('什么时候应该停止实验？', '① 达到预设样本量且统计显著 → 发布 ② 达到预设样本量但无显著差异 → 维持现状 ③ 运行 4 周仍不显著 → 停止实验（可能存在新奇效应）④ 出现负面显著影响 → 立即停止。'),
        ],
        'checks': [
            '实验假设和成功指标已定义',
            '样本量已提前计算',
            '分流均匀性验证通过',
            '互斥实验未冲突',
            '统计显著性达到 95%',
            '实验报告完整',
        ],
        'prompt_sp': '你是一个增长实验专家，精通 A/B 测试的实验设计和统计分析。',
        'prompt_up': '请为以下产品变更设计 A/B 测试方案：\n变更内容：{change_description}\n预期效果：{expected_impact}\n目标指标：{target_metrics}',
        'example_text': "```python\n# A/B 测试分析示例\nimport numpy as np\nfrom scipy import stats\n\n# 实验数据\ncontrol = {'visitors': 50000, 'conversions': 2500, 'rate': 0.05}\ntreatment = {'visitors': 50000, 'conversions': 2750, 'rate': 0.055}\n\n# Z 检验（比例检验）\nz_stat, p_value = stats.proportions_ztest(\n    count=[treatment['conversions'], control['conversions']],\n    nobs=[treatment['visitors'], control['visitors']]\n)\n\n# 置信区间\nfrom statsmodels.stats.proportion import proportion_confint\nci_control = proportion_confint(control['conversions'], control['visitors'], alpha=0.05)\nci_treatment = proportion_confint(treatment['conversions'], treatment['visitors'], alpha=0.05)\n\n# 提升率\neffect_size = (treatment['rate'] - control['rate']) / control['rate']\n\nprint(f'=== A/B 测试结果 ===')\nprint(f'对照组: {control[\"rate\"]:.3f} (95% CI: {ci_control[0]:.3f}-{ci_control[1]:.3f})')\nprint(f'实验组: {treatment[\"rate\"]:.3f} (95% CI: {ci_treatment[0]:.3f}-{ci_treatment[1]:.3f})')\nprint(f'提升率: {effect_size:.1%}')\nprint(f'Z 统计量: {z_stat:.3f}')\nprint(f'p 值: {p_value:.4f}')\nprint(f'统计显著: {\"是\" if p_value < 0.05 else \"否\"}')\n\nif p_value < 0.05 and effect_size > 0:\n    print('\\n结论: 实验版本显著优于对照组，建议发布')\nelse:\n    print('\\n结论: 未达到统计显著性，维持现状')\n```",
        'example_ext': 'py',
    },
}

CAPABILITY = {
    'capability/doc-1/': {
        'title': '能力视图管理',
        'overview': '业务能力视图是架构设计的核心输入，它将企业业务能力按层级结构组织，形成清晰的业务能力地图。本规范定义了能力视图的层级结构、建模方法和更新机制。',
        'principles': ['业务驱动：能力视图从业务视角出发，而非技术视角', '层级清晰：能力按 L1/L2/L3 三级分层', '覆盖完整：视图应覆盖企业全部核心业务能力', '动态更新：能力视图随业务发展持续演进'],
        'rules': [
            ('CAP-VW-001', 'L1 能力域不超过 8 个，每个 L1 下 L2 不超过 6 个', 'P0', '是'),
            ('CAP-VW-002', '能力命名采用 动宾结构（如「订单管理」「风险控制」）', 'P0', '是'),
            ('CAP-VW-003', '每个能力必须明确：能力描述、所属域、依赖关系', 'P0', '是'),
            ('CAP-VW-004', '能力视图至少每年评审更新一次，与业务规划对齐', 'P1', '推荐'),
        ],
        'faqs': [
            ('能力视图和业务架构的关系？', '能力视图是业务架构的核心产出之一。它描述企业「做什么」（业务能力），与「怎么做」（业务流程）和「用什么」（应用架构）共同构成完整的业务架构。'),
            ('如何确保能力视图不遗漏？', '使用价值链分析方法，从端到端的业务流程出发识别所需能力。交叉引用行业标准能力框架（如 BIAN、TM Forum），结合竞品分析补充。'),
        ],
        'checks': [
            'L1/L2 层级结构完整',
            '能力命名符合规范',
            '依赖关系已标注',
            '覆盖核心业务领域',
            '与外部的依赖已识别',
            '评审机制已建立',
        ],
        'prompt_sp': '你是一个企业架构师，精通业务能力建模和架构规划。',
        'prompt_up': '请为以下业务领域设计能力视图：\n业务领域：{business_domain}\n业务范围：{business_scope}\n战略目标：{strategic_goals}',
        'example_text': "```yaml\n# 业务能力视图示例：电商平台\ncapabilities:\n  - domain: 商品管理\n    level: L1\n    capabilities:\n      - name: 商品上架管理\n        level: L2\n        description: 商品信息的创建、审核和发布\n        sub_capabilities:\n          - name: 商品信息录入\n            level: L3\n            description: 商品基本信息、属性、描述的录入\n          - name: 商品审核\n            level: L3\n            description: 商品合规性审核和内容审核\n          - name: 商品发布\n            level: L3\n            description: 商品上架时间和渠道管理\n      - name: 商品定价管理\n        level: L2\n        description: 价格策略制定和调价管理\n  - domain: 订单管理\n    level: L1\n    capabilities:\n      - name: 订单处理\n        level: L2\n        description: 订单创建、支付、发货、售后全流程\n      - name: 履约管理\n        level: L2\n        description: 仓储、配送和签收管理\n```",
        'example_ext': 'yaml',
    },
    'capability/doc-2/': {
        'title': '业务能力映射',
        'overview': '业务能力映射将业务能力与实际业务流程、应用系统和数据资产关联起来，形成业务到 IT 的完整追溯链。本规范定义了映射的方法和产出物标准。',
        'principles': ['双向追溯：从能力可追溯到系统，从系统可映射到能力', '多维度标注：每个映射关系标注支持程度（强/中/弱）', '定期刷新：映射关系随系统变化持续更新', '自动化：优先使用工具维护映射关系而非人工维护'],
        'rules': [
            ('CAP-MAP-001', '每个 L1/L2 能力必须至少映射到一个支撑系统', 'P0', '是'),
            ('CAP-MAP-002', '映射关系必须标注支撑程度：强支撑（核心系统）、中支撑（辅助系统）、弱支撑（手工流程）', 'P0', '是'),
            ('CAP-MAP-003', '能力到应用系统的映射矩阵每季度审查一次', 'P1', '是'),
        ],
        'faqs': [
            ('能力映射的主要用途？', '① 识别 IT 支撑盲区（能力无系统支撑）② 发现重复建设（多系统支撑同一能力）③ 指导投资决策（核心能力对应核心系统优先投资）④ 影响分析（系统下线影响哪些能力）。'),
            ('映射到什么粒度？', 'L1/L2 能力映射到应用系统。L3 能力映射到系统模块/功能。避免过度映射——映射的目的是决策支持，不是穷举。'),
        ],
        'checks': [
            'L1/L2 能力已有系统映射',
            '支撑程度已标注',
            '无能力盲区',
            '无重复建设',
            '映射矩阵已更新',
            '评审机制已执行',
        ],
        'prompt_sp': '你是一个企业架构师，精通业务-IT 对齐和架构治理。',
        'prompt_up': '请为以下能力视图生成映射矩阵：\n能力列表：{capability_list}\n系统清单：{system_inventory}\n映射要求：{mapping_requirements}',
        'example_text': "```yaml\n# 业务能力-应用系统映射矩阵\nmapping:\n  - capability: 商品上架管理\n    level: L2\n    system: 商品管理系统\n    support_level: strong\n    description: 核心能力，商品管理系统的原生功能\n    \n  - capability: 商品上架管理\n    level: L2\n    system: 审核工作台\n    support_level: medium\n    description: 审核流程在工作台中完成\n    \n  - capability: 订单处理\n    level: L2\n    system: 订单中心\n    support_level: strong\n    description: 订单全生命周期管理\n    \n  - capability: 订单处理\n    level: L2\n    system: ERP\n    support_level: medium\n    description: 财务记账和结算\n```",
        'example_ext': 'yaml',
    },
    'capability/doc-3/': {
        'title': '能力成熟度评估',
        'overview': '能力成熟度评估帮助企业了解各项业务能力的发展水平，识别改进方向和优先级。本规范定义了评估的维度和方法。',
        'principles': ['客观评估：基于可验证的证据而非主观感受', '可比较：评估标准统一，不同评估周期可对比', '行动导向：评估结果必须转化为改进计划', '定期执行：至少每年评估一次'],
        'rules': [
            ('CAP-MAT-001', '评估维度包括：流程标准化、系统支撑度、自动化率、效率指标', 'P0', '是'),
            ('CAP-MAT-002', '成熟度分 5 级：初始级、已管理级、已定义级、量化管理级、优化级', 'P0', '是'),
            ('CAP-MAT-003', '每次评估必须有证据支撑（数据、文档、系统截图）', 'P0', '是'),
            ('CAP-MAT-004', '评估结果必须输出差距分析和改进路线图', 'P0', '是'),
        ],
        'checks': [
            '评估维度完整',
            '分级标准统一',
            '评估证据充分',
            '差距分析已完成',
            '改进路线图已输出',
            '改进计划已排期',
        ],
        'prompt_sp': '你是一个企业架构评估专家，精通能力成熟度模型。',
        'prompt_up': '请评估以下能力的成熟度：\n能力名称：{capability_name}\n当前状态：{current_state}\n行业基准：{industry_benchmark}',
        'example_text': "```markdown\n# 能力成熟度评估报告：商品上架管理\n\n## 评估结果\n| 维度 | 当前级别 | 目标级别 | 差距 |\n|------|---------|---------|------|\n| 流程标准化 | L2（已管理） | L4（量化管理） | 中 |\n| 系统支撑度 | L3（已定义） | L4（量化管理） | 低 |\n| 自动化率 | L1（初始） | L3（已定义） | 高 |\n| 效率指标 | L2（已管理） | L4（量化管理） | 中 |\n\n**总体成熟度: L2（已管理级）**\n\n## 差距分析\n1. **流程标准化**: 有基本流程文档但未量化关键指标\n2. **系统支撑度**: 核心功能已系统化但缺乏数据分析能力\n3. **自动化率**: 商品信息录入依赖手工，未使用 OCR/AI 辅助\n4. **效率指标**: 仅统计完成时间，未拆分各环节效率\n\n## 改进路线图\n- Q2: 上线自动化信息录入工具（目标自动化率提升至 60%）\n- Q3: 建立关键效率指标监控体系\n- Q4: 达成 L3 成熟度目标\n```",
        'example_ext': 'md',
    },
    'capability/doc-4/': {
        'title': '能力演进路线图',
        'overview': '能力演进路线图将业务战略转化为具体的 IT 能力提升计划，规划能力的阶段性发展目标和实现路径。',
        'principles': ['战略对齐：路线图必须与企业战略规划保持一致', '价值优先：按业务价值和技术可行性排定优先级', '分阶段演进：能力提升分阶段实施，每阶段有可衡量的成果', '持续调整：路线图每季度回顾调整'],
        'rules': [
            ('CAP-RD-001', '路线图需覆盖 12-24 个月的规划周期', 'P0', '是'),
            ('CAP-RD-002', '每个阶段必须有明确的业务价值目标和验收标准', 'P0', '是'),
            ('CAP-RD-003', '路线图按季度分阶段（近 1-2 季度详细，远 2-4 季度概要）', 'P0', '是'),
            ('CAP-RD-004', '依赖关系和关键里程碑必须标注', 'P1', '推荐'),
        ],
        'checks': [
            '规划周期覆盖 12-24 个月',
            '阶段性目标明确',
            '业务价值可衡量',
            '依赖关系已标注',
            '资源需求已评估',
            '评审机制已建立',
        ],
        'prompt_sp': '你是一个企业架构规划专家，精通 IT 战略规划。',
        'prompt_up': '请为以下能力域设计演进路线图：\n能力域：{capability_domain}\n当前成熟度：{current_maturity}\n目标状态：{target_state}',
        'example_text': "```yaml\n# 能力演进路线图示例\nroadmap:\n  phase_1:\n    timeframe: 2026 Q3\n    focus: 基础能力建设\n    objectives:\n      - 商品信息录入自动化率 >= 60%\n      - 审核流程时效缩短 50%\n    initiatives:\n      - name: 商品信息自动化录入\n        priority: P0\n        effort: 2 个月\n        dependencies: []\n      - name: 审核工作流优化\n        priority: P1\n        effort: 1 个月\n        dependencies: []\n        \n  phase_2:\n    timeframe: 2026 Q4\n    focus: 数据分析能力\n    objectives:\n      - 建立商品运营指标体系\n      - 上线数据看板\n    initiatives:\n      - name: 商品数据仓库建设\n        priority: P1\n        effort: 2 个月\n      - name: 运营指标看板\n        priority: P1\n        effort: 1 个月\n```",
        'example_ext': 'yaml',
    },
}

COMPLIANCE = {
    'compliance/doc-1/': {
        'title': '合规要求管理',
        'overview': '合规要求管理确保产品和业务运营符合法律法规、行业标准和内部政策的要求。本规范建立了合规要求的识别、登记、评估和跟踪机制。',
        'principles': ['全面识别：覆盖法律法规、行业标准和合同义务', '分级管理：按风险等级差异化管控', '持续跟踪：合规要求变化时及时评估影响', '闭环管理：发现问题到整改完成全程跟踪'],
        'rules': [
            ('CMP-001', '所有业务条线必须建立合规要求清单，至少每半年更新一次', 'P0', '是'),
            ('CMP-002', '合规要求必须标注：来源、适用范围、风险等级、合规截止日期', 'P0', '是'),
            ('CMP-003', '高风险合规要求必须有独立验证机制', 'P0', '是'),
            ('CMP-004', '合规差距必须在发现后 30 天内制定整改计划', 'P0', '是'),
        ],
        'faqs': [
            ('合规要求来源有哪些？', '① 法律法规（国家法律、行政法规、地方法规）② 行业标准（ISO、PCI-DSS、等保）③ 合同义务（客户合同的合规条款）④ 内部政策（公司制度的合规要求）。'),
        ],
        'checks': [
            '合规要求清单完整',
            '风险等级评估完成',
            '适用范围已明确',
            '合规截止日期已标注',
            '整改计划已制定',
            '跟踪机制已建立',
        ],
        'prompt_sp': '你是一个合规管理专家，精通企业合规体系的建设和运营。',
        'prompt_up': '请为以下业务场景管理合规要求：\n业务领域：{business_area}\n适用法规：{applicable_regulations}\n现有措施：{current_measures}',
        'example_text': "```yaml\n# 合规要求登记表示例\ncompliance_register:\n  - requirement_id: REG-2024-001\n    title: 个人信息保护法-数据最小化\n    source: 中华人民共和国个人信息保护法\n    article: 第六条\n    risk_level: high\n    scope: 全部收集用户信息的业务\n    deadline: 2024-06-30\n    status: compliant\n    evidence: 数据收集清单审查报告 v2.1\n    owner: 法务部/数据安全组\n```",
        'example_ext': 'yaml',
    },
    'compliance/doc-2/': {
        'title': '审计追踪规范',
        'overview': '审计追踪是记录系统操作行为的关键机制，为安全审计、问题排查和合规取证提供基础数据。本规范定义了审计日志的记录范围、格式、存储和保护要求。',
        'principles': ['全覆盖：关键操作必须有审计记录', '不可篡改：审计日志一经写入不得修改或删除', '可查询：审计日志需要有高效的检索机制', '安全存储：审计日志需要安全加密存储'],
        'rules': [
            ('CMP-AUD-001', '以下操作必须记录审计日志：用户认证、权限变更、数据修改、敏感数据访问', 'P0', '是'),
            ('CMP-AUD-002', '每一条审计日志必须包含：时间戳、操作人、操作类型、操作对象、操作结果、源 IP', 'P0', '是'),
            ('CMP-AUD-003', '审计日志存储周期不少于 180 天，金融类业务不少于 365 天', 'P0', '是'),
            ('CMP-AUD-004', '审计日志需定期归档，归档后不得修改', 'P0', '是'),
        ],
        'checks': [
            '关键操作已全覆盖审计',
            '日志字段完整',
            '存储周期达标',
            '篡改防护已实施',
            '检索功能可用',
            '归档机制已执行',
        ],
        'prompt_sp': '你是一个安全审计专家，精通审计日志体系和合规要求。',
        'prompt_up': '请为以下系统设计审计追踪方案：\n系统名称：{system_name}\n合规要求：{compliance_requirements}\n关键操作：{critical_operations}',
        'example_text': "```sql\n-- 审计日志表设计\nCREATE TABLE audit_log (\n    id BIGINT AUTO_INCREMENT PRIMARY KEY,\n    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    user_id VARCHAR(64) NOT NULL,\n    user_ip VARCHAR(45) NOT NULL,\n    action_type ENUM('CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'PERMISSION_CHANGE') NOT NULL,\n    object_type VARCHAR(64) NOT NULL COMMENT '操作对象类型，如 order, user, product',\n    object_id VARCHAR(64) NOT NULL COMMENT '操作对象 ID',\n    detail JSON COMMENT '操作详情',\n    result ENUM('SUCCESS', 'FAILURE', 'DENIED') NOT NULL,\n    checksum VARCHAR(64) NOT NULL COMMENT '前一条日志的 hash 值，形成链式结构',\n    INDEX idx_timestamp (timestamp),\n    INDEX idx_user (user_id),\n    INDEX idx_action (action_type, object_type),\n    INDEX idx_object (object_type, object_id)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n```",
        'example_ext': 'sql',
    },
    'compliance/doc-3/': {
        'title': '数据隐私合规',
        'overview': '数据隐私合规确保个人信息的收集、存储、处理和传输符合隐私法规要求。本规范涵盖了数据分类、用户授权、数据主体权利响应和隐私影响评估等关键方面。',
        'principles': ['合法正当：数据收集和处理必须有合法基础', '目的限制：数据使用不超出收集时告知的范围', '数据最小化：只收集业务必需的数据', '用户控制：用户对其个人数据拥有完整的控制权'],
        'rules': [
            ('CMP-PRI-001', '所有涉及个人信息的系统必须完成隐私影响评估（PIA）', 'P0', '是'),
            ('CMP-PRI-002', '个人信息收集前必须获得用户的明确同意（Opt-in）', 'P0', '是'),
            ('CMP-PRI-003', '用户数据删除请求必须在 15 个工作日内响应', 'P0', '是'),
            ('CMP-PRI-004', '个人敏感信息（生物识别、金融账户、健康数据）必须加密存储', 'P0', '是'),
            ('CMP-PRI-005', '数据跨境传输必须通过安全评估', 'P0', '是'),
        ],
        'checks': [
            '隐私影响评估已完成',
            '用户同意机制已实现',
            '数据主体权利响应流程已建立',
            '敏感数据已加密',
            '数据出境评估已完成',
            '隐私政策已更新',
        ],
        'prompt_sp': '你是一个数据隐私专家，精通个人信息保护法规和隐私工程。',
        'prompt_up': '请评估以下业务的隐私合规要求：\n业务场景：{business_scenario}\n涉及数据：{personal_data_types}\n适用法规：{applicable_regulations}',
        'example_text': "```yaml\n# 隐私影响评估（PIA）示例\npia:\n  system_name: 用户画像系统\n  data_controller: 市场部\n  processing_purpose: 个性化推荐和精准营销\n  \n  personal_data:\n    - name: 用户基本信息\n      categories: [姓名, 手机号, 邮箱]\n      sensitivity: low\n      retention: 业务关系存续期间\n    - name: 行为数据\n      categories: [浏览记录, 购买历史, 搜索记录]\n      sensitivity: medium\n      retention: 3 年\n    - name: 设备信息\n      categories: [设备 ID, 操作系统, 地理位置]\n      sensitivity: medium\n      retention: 1 年\n  \n  risk_assessment:\n    - risk: 用户画像可能导致隐私泄漏\n      likelihood: medium\n      impact: high\n      mitigation: \n        - 数据脱敏展示\n        - 访问控制（最小权限原则）\n        - 用户可关闭个性化推荐\n```",
        'example_ext': 'yaml',
    },
    'compliance/doc-5/': {
        'title': '合规风险管理',
        'overview': '合规风险管理识别、评估和管控因不合规可能引发的法律、财务和声誉风险。本规范建立合规风险管理的全流程标准。',
        'principles': ['风险导向：按风险等级分配管理资源', '预防为主：在合规问题发生前识别和预防', '动态管理：合规风险评估需随业务和法规变化调整', '闭环管理：发现风险到整改完成全程跟踪'],
        'rules': [
            ('CMP-RM-001', '合规风险按照发生可能性和影响程度分为高/中/低三级', 'P0', '是'),
            ('CMP-RM-002', '高风险合规项必须每月跟踪状态，中风险每季度', 'P0', '是'),
            ('CMP-RM-003', '合规风险登记册必须包含：风险描述、影响分析、整改措施、责任人、截止日期', 'P0', '是'),
            ('CMP-RM-004', '发生合规事件后必须在 24 小时内上报合规委员会', 'P0', '是'),
        ],
        'checks': [
            '风险登记册已建立',
            '风险等级评估完成',
            '跟踪频率已定义',
            '整改责任人已指定',
            '上报机制已建立',
            '合规事件已记录',
        ],
        'prompt_sp': '你是一个风险管理专家，精通 ERM（企业风险管理）框架。',
        'prompt_up': '请评估以下合规风险并制定应对方案：\n业务场景：{business_scenario}\n相关法规：{relevant_regulations}\n现有控制：{existing_controls}',
        'example_text': "```yaml\n# 合规风险登记册\nrisks:\n  - id: CR-2024-001\n    title: 用户数据跨境传输合规风险\n    description: 业务扩张至海外市场，用户数据传输至境外数据中心\n    regulation: 个人信息保护法（跨境传输条款）\n    likelihood: medium\n    impact: high\n    risk_level: high\n    current_controls:\n      - 数据传输加密（TLS 1.3）\n      - 数据分类分级\n    action_plan:\n      - 完成数据出境安全评估\n      - 签署标准合同条款\n      - 设置数据本地化选项\n    owner: 法务部 / IT 安全组\n    deadline: 2026-09-30\n    status: in_progress\n```",
        'example_ext': 'yaml',
    },
    'compliance/gdpr/': {
        'title': 'GDPR 合规指南',
        'overview': 'GDPR（通用数据保护条例）是欧盟的数据保护法规，适用于处理欧盟居民个人数据的所有企业。本指南提供 GDPR 合规的关键要求和最佳实践。',
        'principles': ['权利保障：充分保障数据主体的各项权利', '问责制：企业需证明其合规措施的落实', '隐私设计：将隐私保护融入系统设计全流程', '数据保护影响评估：高风险处理活动必须提前评估'],
        'rules': [
            ('CMP-GDPR-001', '处理欧盟用户数据的业务必须指定欧盟代表', 'P0', '是'),
            ('CMP-GDPR-002', '数据泄露必须在 72 小时内通知监管机构', 'P0', '是'),
            ('CMP-GDPR-003', '数据处理必须有合法依据（同意/合同/法律义务/正当利益）', 'P0', '是'),
            ('CMP-GDPR-004', '用户有权要求数据可移植性（以通用格式导出个人数据）', 'P0', '是'),
            ('CMP-GDPR-005', 'DPO（数据保护官）任命必须在涉及大规模监控或敏感数据处理时完成', 'P0', '是'),
        ],
        'checks': [
            '欧盟代表已指定',
            '数据泄露响应流程已建立',
            '数据处理合法依据已记录',
            '数据主体权利流程已实现',
            'DPO 已任命（如适用）',
            'DPIA 已完成（如适用）',
        ],
        'prompt_sp': '你是一个 GDPR 合规专家，精通欧洲数据保护法规。',
        'prompt_up': '请评估以下业务的 GDPR 合规要求：\n业务场景：{business_scenario}\n涉及数据：{personal_data}\n处理活动：{processing_activities}',
        'example_text': "```yaml\n# GDPR 合规检查清单\ngdpr_checklist:\n  legal_basis:\n    - processing: 订单处理\n      basis: 合同履行（Contractual Necessity）\n      explanation: 处理用户数据是履行购买合同的必要条件\n    - processing: 营销邮件\n      basis: 同意（Consent）\n      explanation: 用户主动订阅营销邮件\n  \n  data_subject_rights:\n    - right: 访问权（Right of Access）\n      implemented: true\n      sla: 30 天内响应\n    - right: 删除权（Right to Erasure）\n      implemented: true\n      sla: 15 个工作日内\n    - right: 数据可移植性（Data Portability）\n      implemented: true\n      format: JSON\n```",
        'example_ext': 'yaml',
    },
}

DOMAIN_CONTENT = {
    'domain/doc-1/': {
        'title': '限界上下文设计',
        'overview': '限界上下文是 DDD（领域驱动设计）的核心概念，它定义了模型和术语的边界。本规范指导如何识别和设计限界上下文。',
        'principles': ['业务边界先行：限界上下文基于业务概念而非技术架构划分', '统一语言：每个上下文内的术语含义唯一', '上下文映射：明确上下文之间的关系和集成方式', '大小适中：上下文不宜过大（难以维护）或过小（通信成本高）'],
        'rules': [
            ('DDD-BC-001', '限界上下文必须基于业务能力和领域专家语言划分', 'P0', '是'),
            ('DDD-BC-002', '每个上下文必须有明确的职责说明和边界定义', 'P0', '是'),
            ('DDD-BC-003', '上下文关系必须使用上下文映射图标注（合作关系/上下游/共享内核等）', 'P0', '是'),
            ('DDD-BC-004', '上下文间的通信最多允许两种方式：事件驱动或 API 调用', 'P1', '推荐'),
        ],
        'faqs': [
            ('限界上下文的粒度如何把握？', '过大：一个上下文中包含多个不相关的业务能力，导致模型臃肿。过小：每个细小功能就是一个上下文，增加集成成本。建议准则：一个上下文对应一个自治的业务能力单元，由 1-2 个团队维护。'),
        ],
        'checks': [
            '边界基于业务概念',
            '职责说明清晰',
            '上下文映射图已绘制',
            '通信方式已定义',
            '统一语言已建立',
            '团队职责已分配',
        ],
        'prompt_sp': '你是一个 DDD 架构专家，精通领域驱动设计和限界上下文建模。',
        'prompt_up': '请识别以下业务领域的限界上下文：\n业务域：{business_domain}\n业务能力：{business_capabilities}\n团队结构：{team_structure}',
        'example_text': "```yaml\n# 限界上下文示例：电商平台\ncontext_map:\n  - name: 商品目录上下文\n    responsibilities:\n      - 商品信息管理\n      - 商品分类和标签\n      - 商品搜索和推荐\n    language: [商品, SKU, 类目, 品牌, 规格]\n    relations:\n      - target: 订单上下文\n        type: upstream\n        integration: 领域事件\n      - target: 库存上下文\n        type: partnership\n        integration: API + 事件\n  - name: 订单上下文\n    responsibilities:\n      - 订单创建和管理\n      - 支付处理\n      - 退款和售后\n    language: [订单, 购物车, 支付单, 退款单]\n    relations:\n      - target: 商品目录上下文\n        type: downstream\n      - target: 用户上下文\n        type: upstream\n```",
        'example_ext': 'yaml',
    },
    'domain/doc-2/': {
        'title': '通用语言定义',
        'overview': '通用语言（Ubiquitous Language）是 DDD 的基石，它是领域专家和开发团队共享的语言。通过统一的术语定义消除沟通歧义。',
        'principles': ['源于业务：术语定义来自业务概念而非技术实现', '双向理解：业务方和技术方对术语有一致的理解', '持续演进：随着业务理解深入，术语定义不断精化', '强制使用：所有沟通和代码中使用统一语言'],
        'rules': [
            ('DDD-UL-001', '每个限界上下文必须有专属的术语表（Glossary）', 'P0', '是'),
            ('DDD-UL-002', '术语定义必须包含：名称、定义、同义词、使用上下文', 'P0', '是'),
            ('DDD-UL-003', '不同上下文中的同名术语必须在术语表中注明歧义', 'P0', '是'),
            ('DDD-UL-004', '代码中的类名和方法名必须与术语表保持一致', 'P1', '是'),
        ],
        'checks': [
            '术语表已建立',
            '术语定义清晰',
            '歧义术语已标注',
            '代码与术语一致',
            '术语表已共享',
            '定期审查机制已建立',
        ],
        'prompt_sp': '你是一个 DDD 实践者，精通通用语言的定义和推广。',
        'prompt_up': '请为以下领域建立通用语言术语表：\n领域名称：{domain_name}\n业务场景：{business_scenarios}\n关键概念：{key_concepts}',
        'example_text': "```yaml\n# 订单上下文 - 通用语言术语表\nglossary:\n  - term: 订单\n    definition: 用户购买商品的法律协议记录，包含商品明细、金额、收货信息\n    synonyms: [交易单, 购买单]\n    context: 订单上下文\n    code: Order (Entity)\n    \n  - term: 购物车\n    definition: 用户暂存待购买商品的临时容器\n    synonyms: [购物篮]\n    context: 订单上下文\n    code: Cart (Entity)\n    \n  - term: 支付单\n    definition: 支付系统生成的支付记录，与订单一一对应\n    synonyms: [支付记录]\n    context: 订单上下文\n    code: Payment (Entity)\n```",
        'example_ext': 'yaml',
    },
    'domain/doc-3/': {
        'title': '聚合设计规范',
        'overview': '聚合（Aggregate）是 DDD 中的一致性边界，确保数据变更的原子性和业务规则的一致性。本规范定义了聚合的设计原则和边界划分标准。',
        'principles': ['一致性边界：聚合内的数据必须满足最终一致性', '聚合根：每个聚合有且仅有一个聚合根实体', '小聚合优先：聚合应尽量小，减少事务范围', '通过 ID 引用：聚合之间通过 ID 而非对象引用'],
        'rules': [
            ('DDD-AGG-001', '聚合必须通过聚合根访问，外部不能直接操作聚合内部实体', 'P0', '是'),
            ('DDD-AGG-002', '一个事务只能修改一个聚合实例', 'P0', '是'),
            ('DDD-AGG-003', '聚合根必须使用全局唯一标识', 'P0', '是'),
            ('DDD-AGG-004', '聚合内实体不超过 5 个，超过应考虑拆分', 'P1', '推荐'),
            ('DDD-AGG-005', '聚合根必须保证不变量（Invariants）的完整性', 'P0', '是'),
        ],
        'checks': [
            '聚合根已识别',
            '一致性边界已定义',
            '跨聚合引用通过 ID',
            '事务范围合理',
            '不变量已确认',
            '聚合大小适中',
        ],
        'prompt_sp': '你是一个 DDD 架构师，精通聚合设计和领域建模。',
        'prompt_up': '请为以下业务能力设计聚合：\n业务能力：{business_capability}\n业务规则：{business_rules}\n数据需求：{data_requirements}',
        'example_text': "```java\n// 订单聚合示例\npublic class Order {\n    private OrderId id;           // 聚合根 ID\n    private OrderStatus status;   // 状态\n    private List<OrderLine> lines; // 内部实体\n    private Address shippingAddress;\n    private Money totalAmount;\n    \n    // 聚合根方法 - 保证不变量\n    public void addItem(ProductId productId, int quantity, Money price) {\n        // 检查订单状态（不可修改已支付的订单）\n        if (status != OrderStatus.DRAFT) {\n            throw new IllegalStateException(\"只能修改草稿状态的订单\");\n        }\n        // 限制最大商品数量\n        if (lines.size() >= 50) {\n            throw new DomainException(\"单笔订单最多 50 件商品\");\n        }\n        lines.add(new OrderLine(productId, quantity, price));\n        recalculateTotal();\n    }\n    \n    public void submit() {\n        // 检查不变量\n        if (lines.isEmpty()) {\n            throw new DomainException(\"订单必须包含至少一件商品\");\n        }\n        // 发布领域事件\n        DomainEventPublisher.publish(new OrderSubmittedEvent(id));\n    }\n}\n```",
        'example_ext': 'java',
    },
    'domain/doc-4/': {
        'title': '领域事件规范',
        'overview': '领域事件捕获业务中发生的具有意义的事件，用于实现限界上下文间的松耦合通信和事件驱动架构。',
        'principles': ['有意义的事件：事件代表业务已发生的事实', '不可变性：事件一经发布不可变更', '幂等性：事件消费方必须支持重复接收', '可追溯：每个事件应有唯一的标识和关联上下文'],
        'rules': [
            ('DDD-EVT-001', '事件命名使用过去时态（如 OrderSubmitted, PaymentReceived）', 'P0', '是'),
            ('DDD-EVT-002', '事件必须包含：event_id、event_type、timestamp、aggregate_id、payload', 'P0', '是'),
            ('DDD-EVT-003', '事件发布必须在聚合根的方法中完成，确保事务一致性', 'P0', '是'),
            ('DDD-EVT-004', '事件消费方必须实现幂等处理', 'P0', '是'),
        ],
        'checks': [
            '事件命名规范',
            '事件字段完整',
            '事务一致性已保障',
            '幂等消费已实现',
            '事件版本已管理',
            '事件文档已更新',
        ],
        'prompt_sp': '你是一个事件驱动架构专家，精通领域事件设计。',
        'prompt_up': '请为以下业务场景设计领域事件：\n业务域：{business_domain}\n业务流程：{business_process}\n需要通知的上下文：{subscribing_contexts}',
        'example_text': "```java\n// 领域事件定义示例\n@Value\npublic class OrderSubmittedEvent implements DomainEvent {\n    EventId eventId = EventId.generate();\n    Instant occurredAt = Instant.now();\n    OrderId orderId;\n    UserId customerId;\n    Money totalAmount;\n    String eventType = \"order.submitted\";\n    int version = 1;\n}\n\n// 事件发布（在聚合根方法中）\npublic class Order {\n    public void submit() {\n        validateForSubmission();\n        this.status = OrderStatus.SUBMITTED;\n        \n        // 注册待发布事件（由基础设施在保存后自动发布）\n        registerEvent(new OrderSubmittedEvent(this.id, this.customerId, this.totalAmount));\n    }\n}\n\n// 事件消费（幂等处理）\n@Component\npublic class InventoryEventHandler {\n    @EventListener\n    public void on(OrderSubmittedEvent event) {\n        // 幂等校验\n        if (processedEventRepository.exists(event.getEventId())) {\n            log.info(\"Event already processed: {}\", event.getEventId());\n            return;\n        }\n        // 扣减库存\n        inventoryService.reserveStock(event.getOrderId());\n        // 记录已处理事件\n        processedEventRepository.save(new ProcessedEvent(event.getEventId()));\n    }\n}\n```",
        'example_ext': 'java',
    },
    'domain/doc-5/': {
        'title': '值对象实现',
        'overview': '值对象（Value Object）是 DDD 中的重要概念，它描述事物的属性特征但不具备独立身份。本规范定义了值对象的设计标准和实现规范。',
        'principles': ['不可变性：值对象一旦创建不可修改', '无身份标识：值对象没有唯一 ID', '值相等：两个值对象当所有属性相等时视为相同', '自包含行为：值对象应包含自身的验证和行为逻辑'],
        'rules': [
            ('DDD-VO-001', '值对象必须为不可变（所有属性在构造后不可修改）', 'P0', '是'),
            ('DDD-VO-002', '值对象必须实现 equals 和 hashCode 方法（基于值的比较）', 'P0', '是'),
            ('DDD-VO-003', '值对象应包含自验证逻辑，不依赖外部进行校验', 'P0', '是'),
            ('DDD-VO-004', '值对象可与实体关联，但不能取代实体的身份', 'P1', '推荐'),
        ],
        'checks': [
            '值对象不可变',
            '值相等已实现',
            '自验证逻辑已包含',
            '身份标识不存在',
            '行为方法已添加',
            '使用合理（值对象 vs 实体已判断）',
        ],
        'prompt_sp': '你是一个 DDD 实践者，精通领域建模和值对象设计。',
        'prompt_up': '请为以下业务概念设计值对象：\n概念名称：{concept_name}\n属性定义：{attribute_definition}\n业务约束：{business_constraints}',
        'example_text': "```java\n// 值对象示例\npublic final class Money implements ValueObject {\n    private final BigDecimal amount;\n    private final Currency currency;\n    \n    public Money(BigDecimal amount, Currency currency) {\n        // 自验证逻辑\n        if (amount == null || currency == null) {\n            throw new IllegalArgumentException(\"金额和货币不能为空\");\n        }\n        if (amount.compareTo(BigDecimal.ZERO) < 0) {\n            throw new IllegalArgumentException(\"金额不能为负数\");\n        }\n        if (amount.scale() > 2) {\n            throw new IllegalArgumentException(\"金额精度最多小数点后 2 位\");\n        }\n        this.amount = amount;\n        this.currency = currency;\n    }\n    \n    // 行为方法\n    public Money add(Money other) {\n        if (!this.currency.equals(other.currency)) {\n            throw new IllegalArgumentException(\"货币类型不一致\");\n        }\n        return new Money(this.amount.add(other.amount), this.currency);\n    }\n    \n    public Money multiply(int factor) {\n        return new Money(this.amount.multiply(BigDecimal.valueOf(factor)), this.currency);\n    }\n    \n    // 值相等\n    @Override\n    public boolean equals(Object o) {\n        if (this == o) return true;\n        if (o == null || getClass() != o.getClass()) return false;\n        Money money = (Money) o;\n        return amount.compareTo(money.amount) == 0 && currency.equals(money.currency);\n    }\n    \n    @Override\n    public int hashCode() {\n        return Objects.hash(amount, currency);\n    }\n}\n```",
        'example_ext': 'java',
    },
}

EVENT_CONTENT = {
    'event/doc-1/': {
        'title': '事件驱动架构原则',
        'overview': '事件驱动架构（EDA）通过事件的产生、检测和消费来实现系统间的松耦合通信。本规范定义了 EDA 的核心原则、事件分类和架构选型标准。',
        'principles': ['松耦合：生产者和消费者不直接依赖', '最终一致性：通过异步事件实现系统间最终一致', '幂等消费：消费者必须支持事件重复接收', '事件溯源优先：重要业务状态变化通过事件记录'],
        'rules': [
            ('EDA-PR-001', '核心业务实体状态变更必须发布领域事件', 'P0', '是'),
            ('EDA-PR-002', '事件生产者和消费者之间必须通过消息中间件解耦', 'P0', '是'),
            ('EDA-PR-003', '事件必须包含完整的业务上下文，消费者不应额外查询', 'P0', '是'),
            ('EDA-PR-004', '事件消费必须实现幂等性（去重机制）', 'P0', '是'),
            ('EDA-PR-005', '事件处理失败必须有重试和死信队列机制', 'P0', '是'),
        ],
        'checks': [
            '领域事件已识别',
            '消息中间件已选型',
            '事件格式已定义',
            '幂等消费已实现',
            '重试机制已配置',
            '死信队列已设置',
        ],
        'prompt_sp': '你是一个事件驱动架构师，精通分布式系统设计。',
        'prompt_up': '请为以下业务场景设计事件驱动方案：\n业务场景：{business_scenario}\n系统架构：{system_architecture}\n集成需求：{integration_requirements}',
        'example_text': "```yaml\n# 事件驱动架构示例\narchitecture:\n  event_bus: Apache Kafka\n  \n  topics:\n    - name: order.events\n      partitions: 6\n      retention: 7d\n      events:\n        - OrderSubmitted\n        - OrderPaid\n        - OrderShipped\n      consumers:\n        - InventoryService (扣减库存)\n        - NotificationService (发送通知)\n        - AnalyticsService (数据分析)\n    \n    - name: payment.events\n      partitions: 3\n      retention: 30d\n      events:\n        - PaymentReceived\n        - PaymentRefunded\n      consumers:\n        - OrderService (更新订单状态)\n        - AccountingService (记账)\n```",
        'example_ext': 'yaml',
    },
    'event/doc-2/': {
        'title': '事件契约标准',
        'overview': '事件契约是事件生产者和消费者之间的协议，定义了事件的格式、字段和语义。标准化的事件契约是保障事件驱动系统可靠运行的基础。',
        'principles': ['Schema 优先：事件格式必须通过 Schema 定义', '向后兼容：Schema 变更不能破坏已有消费者', '版本化管理：事件 Schema 需要版本化并允许共存', '契约测试：生产者和消费者需通过契约测试验证兼容性'],
        'rules': [
            ('EDA-CTG-001', '所有业务事件必须使用 Avro/Protobuf/JSON Schema 定义格式', 'P0', '是'),
            ('EDA-CTG-002', '事件字段只允许新增，不允许修改或删除已有字段', 'P0', '是'),
            ('EDA-CTG-003', '新增字段必须标记为 optional，且提供默认值', 'P0', '是'),
            ('EDA-CTG-004', 'Schema 变更必须通过兼容性校验（向后兼容）', 'P0', '是'),
            ('EDA-CTG-005', '每个事件必须包含 event_schema_version 字段', 'P1', '推荐'),
        ],
        'checks': [
            '事件 Schema 已定义',
            'Schema 注册表已配置',
            '向后兼容性已验证',
            '版本号已标注',
            '契约测试已通过',
            '文档已更新',
        ],
        'prompt_sp': '你是一个事件架构师，精通事件契约设计和 Schema 管理。',
        'prompt_up': '请为以下事件设计契约标准：\n事件名称：{event_name}\n业务场景：{business_context}\n消费者需求：{consumer_requirements}',
        'example_text': "```avro\n{\n  \"type\": \"record\",\n  \"namespace\": \"com.example.order\",\n  \"name\": \"OrderSubmitted\",\n  \"doc\": \"用户提交订单后发布\",\n  \"fields\": [\n    {\"name\": \"event_id\", \"type\": \"string\", \"doc\": \"事件唯一标识\"},\n    {\"name\": \"event_version\", \"type\": \"int\", \"default\": 1},\n    {\"name\": \"timestamp\", \"type\": \"long\", \"doc\": \"事件发生时间戳\"},\n    {\"name\": \"order_id\", \"type\": \"string\"},\n    {\"name\": \"customer_id\", \"type\": \"string\"},\n    {\"name\": \"total_amount\", \"type\": \"double\"},\n    {\"name\": \"currency\", \"type\": \"string\", \"default\": \"CNY\"},\n    {\"name\": \"items\", \"type\": {\"type\": \"array\", \"items\": {\n      \"type\": \"record\",\n      \"name\": \"OrderItem\",\n      \"fields\": [\n        {\"name\": \"product_id\", \"type\": \"string\"},\n        {\"name\": \"quantity\", \"type\": \"int\"},\n        {\"name\": \"price\", \"type\": \"double\"}\n      ]\n    }}}\n  ]\n}\n```",
        'example_ext': 'avsc',
    },
    'event/doc-3/': {
        'title': '事件溯源模式',
        'overview': '事件溯源（Event Sourcing）将应用程序状态的每次变更保存为一系列事件，而非直接存储当前状态。通过重放事件可以重建任意历史状态。',
        'principles': ['事件即真相：事件是状态的唯一权威来源', '可重放：通过事件重放可重建任意时间点状态', '完整记录：所有状态变更都有事件留存', '快照优化：定期创建快照减少重放开销'],
        'rules': [
            ('EDA-ES-001', '事件存储必须是仅追加（Append-only），事件不可修改或删除', 'P0', '是'),
            ('EDA-ES-002', '重大数据变更必须通过事件溯源记录', 'P1', '推荐'),
            ('EDA-ES-003', '事件存储必须支持按聚合 ID 和事件序列号顺序读取', 'P0', '是'),
            ('EDA-ES-004', '每 N 个事件后创建一次快照（建议 N=100）', 'P1', '推荐'),
            ('EDA-ES-005', '快照存储需压缩以减少存储成本', 'P2', '推荐'),
        ],
        'checks': [
            '事件存储方式已确定',
            'Append-only 已实施',
            '事件读取接口已实现',
            '快照机制已配置',
            '快照压缩已启用',
            '主流恢复流程已验证',
        ],
        'prompt_sp': '你是一个事件溯源专家，精通 CQRS/ES 架构模式。',
        'prompt_up': '请为以下聚合设计事件溯源方案：\n聚合名称：{aggregate_name}\n业务事件：{business_events}\n状态快照要求：{snapshot_requirements}',
        'example_text': "```python\n# 事件溯源示例：订单聚合\nfrom dataclasses import dataclass\nfrom enum import Enum\n\nclass OrderStatus(Enum):\n    DRAFT = 'draft'\n    SUBMITTED = 'submitted'\n    PAID = 'paid'\n    SHIPPED = 'shipped'\n\n@dataclass\nclass OrderState:\n    order_id: str\n    status: OrderStatus\n    items: list\n    total_amount: float\n    version: int\n    \nclass OrderAggregate:\n    def __init__(self):\n        self.state = None\n        self.changes = []\n    \n    def load_from_history(self, events):\n        self.state = None\n        for event in events:\n            self._apply(event)\n    \n    def submit(self, order_id, items):\n        event = OrderSubmitted(order_id, items, sum(i['price']*i['qty'] for i in items))\n        self._apply(event)\n        self.changes.append(event)\n    \n    def pay(self, payment_id):\n        event = OrderPaid(self.state.order_id, payment_id)\n        self._apply(event)\n        self.changes.append(event)\n    \n    def _apply(self, event):\n        if isinstance(event, OrderSubmitted):\n            self.state = OrderState(\n                order_id=event.order_id,\n                status=OrderStatus.SUBMITTED,\n                items=event.items,\n                total_amount=event.total,\n                version=1\n            )\n        elif isinstance(event, OrderPaid):\n            self.state.status = OrderStatus.PAID\n            self.state.version += 1\n```",
        'example_ext': 'py',
    },
    'event/doc-5/': {
        'title': '消息中间件选型',
        'overview': '选择合适的消息中间件是事件驱动架构成功的关键。本规范覆盖了主流消息中间件的对比、选型标准和集成模式。',
        'principles': ['需求匹配：选型基于业务场景而非技术偏好', '运维成本：考虑部署、监控和维护的长期成本', '生态兼容：与现有技术栈的集成度', '社区活跃：选择有活跃社区支持的成熟产品'],
        'rules': [
            ('EDA-MQ-001', '消息中间件选型必须考虑：吞吐量、延迟、持久性、可用性、顺序保证', 'P0', '是'),
            ('EDA-MQ-002', '核心业务消息必须通过选型评审，包含 POC 验证', 'P0', '是'),
            ('EDA-MQ-003', '消息大小超过 1MB 必须使用对象存储引用方式', 'P0', '是'),
            ('EDA-MQ-004', '消息中间件必须部署为集群模式，保障高可用', 'P0', '是'),
        ],
        'checks': [
            '选型评估完成',
            'POC 验证通过',
            '集群模式已部署',
            '监控告警已配置',
            '消息大小限制已确认',
            '灾备方案已准备',
        ],
        'prompt_sp': '你是一个消息中间件专家，精通 MQ 产品选型和架构设计。',
        'prompt_up': '请为以下场景推荐消息中间件：\n业务场景：{business_scenario}\n技术要求：{technical_requirements}\n现有技术栈：{current_tech_stack}',
        'example_text': "```yaml\n# 消息中间件选型对比\ncomparison:\n  - product: Apache Kafka\n    throughput: 极高（百万 msg/s）\n    latency: 低（10ms 级）\n    persistence: 磁盘持久化\n    ordering: Partition 内有序\n    use_cases:\n      - 日志收集和聚合\n      - 数据管道和流处理\n      - 事件溯源\n      - 埋点数据采集\n      \n  - product: RabbitMQ\n    throughput: 高（万 msg/s）\n    latency: 极低（微秒级）\n    persistence: 内存/磁盘\n    ordering: 队列内有序\n    use_cases:\n      - 任务队列\n      - RPC 调用\n      - 异步消息通知\n      - 事务消息\n      \n  - product: Apache Pulsar\n    throughput: 极高（百万 msg/s）\n    latency: 低\n    persistence: 分层存储\n    ordering: Partition 内有序\n    use_cases:\n      - 多租户消息系统\n      - 异地多活\n      - 消息堆积处理\n```",
        'example_ext': 'yaml',
    },
    'event/cqrs/': {
        'title': 'CQRS 模式',
        'overview': 'CQRS（命令查询职责分离）将读写操作分离为不同的模型和数据库，优化系统的查询性能和命令处理。',
        'principles': ['读写分离：命令模型和查询模型独立演进', '命令侧使用领域模型，查询侧使用投影模型', '最终一致性：读模型可能落后于写模型', '按需投影：查询模型针对特定查询场景优化'],
        'rules': [
            ('EDA-CQRS-001', '命令必须使用领域模型处理，包含完整的业务验证', 'P0', '是'),
            ('EDA-CQRS-002', '查询模型必须从事件投影构建，不能直接操作命令数据库', 'P0', '是'),
            ('EDA-CQRS-003', '查询模型可以包含反范式化数据以优化查询性能', 'P0', '是'),
            ('EDA-CQRS-004', '读库和写库的数据同步延迟必须在 SLA 范围内', 'P1', '推荐'),
        ],
        'checks': [
            '命令和查询模型已分离',
            '事件投影已实现',
            '查询模型已优化',
            '数据同步延迟已监控',
            '最终一致性已说明',
            'SLA 已定义',
        ],
        'prompt_sp': '你是一个 CQRS/ES 架构专家，精通读写分离和事件投影。',
        'prompt_up': '请为以下业务设计 CQRS 方案：\n业务场景：{business_scenario}\n查询需求：{query_requirements}\n命令需求：{command_requirements}',
        'example_text': "```yaml\n# CQRS 架构示例\ncqrs:\n  command_side:\n    model: 领域模型（Order Aggregate）\n    database: PostgreSQL（写库）\n    api: POST /api/orders（创建订单）\n    \n  event_side:\n    events:\n      - OrderSubmitted\n      - OrderPaid\n      - OrderShipped\n    event_store: Apache Kafka\n    \n  query_side:\n    projections:\n      - name: OrderSummaryProjection\n        purpose: 订单列表展示\n        database: MongoDB（读库）\n        schema:\n          orderId: string\n          customerName: string\n          totalAmount: number\n          status: string\n          createdAt: date\n        events_consumed:\n          - OrderSubmitted\n          - OrderPaid\n          - OrderShipped\n          \n      - name: OrderDetailProjection\n        purpose: 订单详情展示\n        database: Elasticsearch\n        schema:\n          orderId: string\n          customer: object\n          items: array\n          payments: array\n          timeline: array\n```",
        'example_ext': 'yaml',
    },
}

OPERATION_CONTENT = {
    'operation/doc-1/': {
        'title': '监控告警标准',
        'overview': '监控告警是保障系统稳定性的第一道防线。本规范定义了监控指标、告警规则、通知策略和值班响应的标准。',
        'principles': ['全面监控：覆盖基础设施、应用性能、业务指标', '告警分级：按严重程度差异化响应', '减少噪音：告警要有明确的可行动作', '持续优化：定期审核告警规则消除无效告警'],
        'rules': [
            ('OPS-MON-001', '每个服务必须监控：CPU、内存、GC、请求数、错误率、响应时间', 'P0', '是'),
            ('OPS-MON-002', '告警分为 P0（紧急）/P1（严重）/P2（警告）/P3（通知）四级', 'P0', '是'),
            ('OPS-MON-003', 'P0 告警必须 5 分钟内通知到值班人员，P1 告警 15 分钟内', 'P0', '是'),
            ('OPS-MON-004', '告警必须有明确的解决步骤文档（Runbook）', 'P0', '是'),
            ('OPS-MON-005', '每周统计告警噪音率（误报/无需行动的告警），目标 < 10%', 'P1', '推荐'),
        ],
        'checks': [
            '四大黄金指标已监控',
            '告警分级已完成',
            '通知渠道已配置',
            'Runbook 已建立',
            '值班轮换已安排',
            '告警噪音率已统计',
        ],
        'prompt_sp': '你是一个 SRE 专家，精通监控告警体系的设计和运维。',
        'prompt_up': '请为以下服务设计监控告警方案：\n服务名称：{service_name}\n业务关键指标：{business_kpis}\nSLA 要求：{sla_requirements}',
        'example_text': "```yaml\n# 监控告警规则示例\nalerts:\n  - name: HighErrorRate\n    metric: http_request_error_rate\n    condition: '> 5%'\n    duration: 5m\n    severity: P1\n    description: 服务错误率超过 5%\n    runbook: |\n      1. 检查最近部署变更\n      2. 查看日志定位错误原因\n      3. 如数据库超时检查连接池\n    \n  - name: P99LatencyHigh\n    metric: http_request_p99\n    condition: '> 2000ms'\n    duration: 10m\n    severity: P1\n    \n  - name: DiskUsageWarning\n    metric: disk_usage_percent\n    condition: '> 85%'\n    duration: 30m\n    severity: P2\n```",
        'example_ext': 'yaml',
    },
    'operation/doc-2/': {
        'title': '日志管理规范',
        'overview': '日志是系统运行状态的客观记录，在问题排查、安全审计和业务分析中发挥关键作用。本规范定义了日志的分类、格式、采集和存储标准。',
        'principles': ['结构化：日志采用统一的结构化格式（JSON）', '分级记录：按日志级别区分重要性', '合理采样：高流量日志做采样处理', '安全合规：日志不能包含敏感信息'],
        'rules': [
            ('OPS-LOG-001', '所有应用日志必须使用结构化格式（JSON），包含：timestamp、level、logger、message、trace_id', 'P0', '是'),
            ('OPS-LOG-002', '日志级别分五级：TRACE < DEBUG < INFO < WARN < ERROR', 'P0', '是'),
            ('OPS-LOG-003', '生产环境日志级别默认为 INFO，DEBUG 级别需动态开启', 'P0', '是'),
            ('OPS-LOG-004', '日志中禁止记录密码、Token、身份证号等敏感信息', 'P0', '是'),
            ('OPS-LOG-005', '日志存储周期：ERROR 日志 30 天，INFO 日志 15 天，DEBUG 日志 7 天', 'P1', '推荐'),
        ],
        'checks': [
            '日志格式已统一',
            '日志级别设置合理',
            '敏感信息过滤已实施',
            '日志采集已配置',
            '存储周期已定义',
            '日志归档机制已建立',
        ],
        'prompt_sp': '你是一个可观测性专家，精通日志管理和 ELK/Loki 技术栈。',
        'prompt_up': '请为以下应用设计日志方案：\n应用类型：{app_type}\n技术栈：{tech_stack}\n合规要求：{compliance_requirements}',
        'example_text': "```json\n// 结构化日志示例\n{\n  \"timestamp\": \"2026-06-28T10:30:00.123+08:00\",\n  \"level\": \"ERROR\",\n  \"logger\": \"com.example.order.OrderService\",\n  \"message\": \"订单创建失败：库存不足\",\n  \"trace_id\": \"trace-abc-123\",\n  \"span_id\": \"span-xyz-456\",\n  \"context\": {\n    \"order_id\": \"ORD-20240628-001\",\n    \"user_id\": \"USR-10086\",\n    \"product_id\": \"PROD-888\",\n    \"requested_qty\": 10,\n    \"available_qty\": 3\n  },\n  \"exception\": {\n    \"class\": \"InsufficientStockException\",\n    \"message\": \"商品库存不足，可用: 3，请求: 10\",\n    \"stack_trace\": \"...\"\n  },\n  \"host\": \"app-server-01\",\n  \"environment\": \"production\"\n}\n```",
        'example_ext': 'json',
    },
    'operation/doc-3/': {
        'title': '故障应急响应',
        'overview': '故障应急响应确保在系统异常时快速恢复服务，减少对业务的影响。本规范定义了故障的分级、响应流程、处理步骤和复盘机制。',
        'principles': ['恢复优先：第一时间恢复服务，根因分析后置', '明确分工：故障处理有明确的指挥官和技术负责人', '充分沟通：及时同步故障状态给利益相关方', '复盘改进：每次故障必须复盘并跟进改进措施'],
        'rules': [
            ('OPS-IR-001', 'P0 故障必须在 10 分钟内恢复服务，P1 故障在 30 分钟内', 'P0', '是'),
            ('OPS-IR-002', '故障指挥官（IC）负责协调处理，不得同时参与技术排查', 'P0', '是'),
            ('OPS-IR-003', '故障状态每 30 分钟同步一次给利益相关方', 'P0', '是'),
            ('OPS-IR-004', 'P0/P1 故障后 48 小时内必须完成复盘报告', 'P0', '是'),
            ('OPS-IR-005', '复盘必须有 5 Whys 根因分析和可量化的改进措施', 'P0', '是'),
        ],
        'checks': [
            '故障分级标准已定义',
            '应急响应团队已组建',
            '通知渠道已生效',
            'Runbook 已准备',
            '复盘机制已建立',
            '改进措施已跟踪',
        ],
        'prompt_sp': '你是一个 SRE 专家，精通故障应急响应和 ITIL 流程。',
        'prompt_up': '请为以下故障事件制定应急响应流程：\n故障类型：{failure_type}\n影响范围：{impact_scope}\n系统架构：{system_architecture}',
        'example_text': "```markdown\n# 故障复盘报告\n\n## 事件概要\n- **故障 ID**: INC-2026-001\n- **标题**: 订单服务 OOM 导致全站下单失败\n- **等级**: P0\n- **时间线**:\n  - 10:05 监控告警触发（错误率 > 30%）\n  - 10:08 值班工程师确认故障，启动应急\n  - 10:12 故障指挥官确认\n  - 10:15 定位到订单服务 OOM\n  - 10:20 订单服务重启恢复\n  - 10:35 错误率恢复正常\n\n## 根因分析（5 Whys）\n1. 为什么订单服务 OOM？→ 内存泄漏\n2. 为什么发生内存泄漏？→ 线程池未释放\n3. 为什么线程池未释放？→ 异常处理未释放资源\n\n## 改进措施\n| 措施 | 负责人 | 截止日期 |\n|------|--------|---------|\n| 修复线程池资源泄漏 | 张三 | 2026-07-05 |\n| 增加 OOM 自动重启机制 | 李四 | 2026-06-30 |\n| 增加堆内存使用监控告警 | 王五 | 2026-07-01 |\n```",
        'example_ext': 'md',
    },
    'operation/sla-slo-sli/': {
        'title': 'SLA/SLO/SLI 体系',
        'overview': 'SLA（服务等级协议）、SLO（服务等级目标）和 SLI（服务等级指标）是服务质量管理的基础框架。本规范定义了三类指标的制定标准和评估方法。',
        'principles': ['可量化：所有指标必须可测量、可监控', '基于用户视角：SLO 从用户体验出发而非技术指标', '错误预算：使用 SLO 达标率控制变更节奏', '持续改进：定期评估和调整 SLO'],
        'rules': [
            ('OPS-SLO-001', '每个外部面向的服务必须定义 SLI、SLO 和 SLA', 'P0', '是'),
            ('OPS-SLO-002', 'SLI 包括：可用性、延迟、吞吐量、错误率、饱和度', 'P0', '是'),
            ('OPS-SLO-003', 'SLO 目标建议值：可用性 99.9%+、P99 延迟 < 1s、错误率 < 0.1%', 'P0', '是'),
            ('OPS-SLO-004', '错误预算月度消耗 100% 时应触发变更冻结', 'P0', '是'),
            ('OPS-SLO-005', 'SLO 达标情况必须每月审查并报告给业务方', 'P1', '推荐'),
        ],
        'checks': [
            'SLI/SLO/SLA 已定义',
            'SLI 可监控可测量',
            'SLO 目标值已确认',
            '错误预算机制已实施',
            '月度审查已安排',
            'SLA 违约补偿已定义',
        ],
        'prompt_sp': '你是一个 SRE 专家，精通服务等级指标体系和可靠性工程。',
        'prompt_up': '请为以下服务设计 SLO 体系：\n服务名称：{service_name}\n用户场景：{user_scenarios}\n业务要求：{business_requirements}',
        'example_text': "```yaml\n# SLO 体系定义\nservice:\n  name: 订单服务\n\nslis:\n  - name: 可用性\n    measurement: 请求成功数 / 总请求数\n    threshold: '>= 99.95%'\n    window: 30天\n    \n  - name: 延迟（P99）\n    measurement: 响应时间的第 99 百分位\n    threshold: '<= 1000ms'\n    window: 30天\n    \n  - name: 延迟（P50）\n    measurement: 响应时间的中位数\n    threshold: '<= 200ms'\n    window: 30天\n\nslos:\n  - name: 核心交易 API 可用性\n    target: '99.95%'\n    measurement_window: 30d\n    error_budget: 0.05%（约 21.6 分钟/月）\n    \nerror_budget:\n  policy: 当月错误预算消耗 >= 70% 时，变更需要经理审批\n  policy: 当月错误预算消耗 100% 时，变更冻结\n  remaining: 65%（本月剩余）\n```",
        'example_ext': 'yaml',
    },
}

PERFORMANCE_CONTENT = {
    'performance/doc-1/': {
        'title': '性能指标体系',
        'overview': '性能指标体系是量化评估系统性能的基础。本规范定义了关键性能指标的分类、测量方法和目标值标准。',
        'principles': ['端到端：覆盖前端到后端到数据库的全链路', '用户视角：指标反映最终用户的真实体验', '可对比：指标有统一的测量口径和基准线', '趋势导向：关注指标随时间的变化趋势而非绝对值'],
        'rules': [
            ('PERF-MET-001', '性能指标分为三类：用户体验指标、系统指标、资源指标', 'P0', '是'),
            ('PERF-MET-002', '用户体验指标必须包含：LCP、FID/INP、CLS（Web 核心指标）', 'P0', '是'),
            ('PERF-MET-003', '系统指标必须包含：P50/P95/P99 延迟、吞吐量、错误率', 'P0', '是'),
            ('PERF-MET-004', '所有性能指标必须有明确的采集方式和计算口径', 'P0', '是'),
            ('PERF-MET-005', '性能基线每月更新一次，反映系统性能趋势', 'P1', '推荐'),
        ],
        'checks': [
            '三类指标已定义',
            'Web Core Vitals 已采集',
            '延迟百分位已监控',
            '采集方式已确定',
            '性能基线已建立',
            '仪表盘已配置',
        ],
        'prompt_sp': '你是一个性能工程专家，精通性能指标体系和测量方法。',
        'prompt_up': '请为以下系统设计性能指标体系：\n系统名称：{system_name}\n用户场景：{user_scenarios}\n技术栈：{tech_stack}',
        'example_text': "```yaml\n# Web 应用性能指标体系\nmetrics:\n  # 用户体验指标\n  user_experience:\n    - name: LCP (Largest Contentful Paint)\n      target: '< 2.5s'\n      measurement: 从导航开始到最大内容元素渲染\n      \n    - name: INP (Interaction to Next Paint)\n      target: '< 200ms'\n      measurement: 用户交互到下一次渲染的延迟\n      \n    - name: CLS (Cumulative Layout Shift)\n      target: '< 0.1'\n      measurement: 页面内容意外位移的累积分数\n\n  # 后端指标\n  backend:\n    - name: API P99 Latency\n      target: '< 1000ms'\n      measurement: 响应时间第 99 百分位\n    - name: API P95 Latency\n      target: '< 500ms'\n    - name: Throughput\n      target: '>= 1000 req/s'\n    - name: Error Rate\n      target: '< 0.1%'\n\n  # 资源指标\n  resources:\n    - name: CPU Usage\n      target: '< 70%'\n    - name: Memory Usage\n      target: '< 80%'\n    - name: GC Pause Time\n      target: P99 < 100ms\n```",
        'example_ext': 'yaml',
    },
    'performance/doc-2/': {
        'title': '基准测试规范',
        'overview': '基准测试（Benchmark Testing）是量化系统性能基线的方法。本规范定义了基准测试的场景设计、执行流程和结果分析方法。',
        'principles': ['可复现：测试环境、数据和脚本需可重复执行', '隔离性：基准测试在隔离环境中执行', '数据驱动：基于历史数据设计测试场景', '版本对比：每次基准测试结果需与历史版本对比'],
        'rules': [
            ('PERF-BENCH-001', '基准测试必须在与生产环境配置一致的隔离环境中执行', 'P0', '是'),
            ('PERF-BENCH-002', '测试数据量需达到生产环境的 50% 以上', 'P0', '是'),
            ('PERF-BENCH-003', '每次基准测试至少运行 3 次取中位数', 'P0', '是'),
            ('PERF-BENCH-004', '基准测试结果需与上一次基准测试结果对比，偏差超过 15% 需分析原因', 'P0', '是'),
            ('PERF-BENCH-005', '基准测试脚本和数据版本化管理', 'P1', '推荐'),
        ],
        'checks': [
            '测试环境已就绪',
            '测试数据已准备',
            '测试脚本已版本化',
            '基线已建立',
            '结果对比已完成',
            '报告已生成',
        ],
        'prompt_sp': '你是一个性能测试专家，精通基准测试和负载测试。',
        'prompt_up': '请为以下系统设计基准测试方案：\n系统架构：{system_architecture}\n核心场景：{core_scenarios}\n性能要求：{performance_requirements}',
        'example_text': "```yaml\n# 基准测试方案\nbenchmark:\n  service: 订单服务 API\n  \n  environment:\n    spec: 4C8G × 3 实例\n    db: PostgreSQL 16, 4C16G\n    data_size: 500 万订单记录\n  \n  scenarios:\n    - name: 创建订单\n      target_api: POST /api/orders\n      payload_size: 2KB\n      target_tps: 500\n      variant: 10% 中包含 50+ 商品大订单\n      \n    - name: 查询订单列表\n      target_api: GET /api/orders\n      query_params: page, size(10/20/50), status\n      target_tps: 2000\n  \n  execution:\n    warmup: 30s（50% target rate）\n    duration: 5min\n    iterations: 3\n    cooldown: 60s\n```",
        'example_ext': 'yaml',
    },
    'performance/doc-3/': {
        'title': '性能优化模式',
        'overview': '性能优化模式是解决常见性能问题的可重复方案。本规范整理了缓存策略、并发模型、查询优化等性能优化模式的适用场景和实施方法。',
        'principles': ['测量优先：在优化前先测量瓶颈位置', '最小改动：每次只做一项优化并验证效果', '权衡取舍：性能优化与代码可维护性之间寻找平衡', '渐进优化：从最大收益处开始，逐步优化'],
        'rules': [
            ('PERF-OPT-001', '性能优化前必须通过 Profiling 定位瓶颈，禁止凭猜测优化', 'P0', '是'),
            ('PERF-OPT-002', '每次优化只修改一处，优化后必须重新测量对比', 'P0', '是'),
            ('PERF-OPT-003', '缓存策略需考虑：缓存命中率、过期策略、缓存穿透/击穿/雪崩防护', 'P0', '是'),
            ('PERF-OPT-004', 'N+1 查询问题必须通过批量查询或懒加载优化', 'P0', '是'),
            ('PERF-OPT-005', '数据库慢查询（> 1s）必须优化，长期慢查询必须有优化计划', 'P0', '是'),
        ],
        'checks': [
            '瓶颈已定位（Profiling 完成）',
            '优化方案已确定',
            '优化效果已测量',
            '缓存策略已评估',
            'N+1 问题已排查',
            '慢查询已优化',
        ],
        'prompt_sp': '你是一个性能优化专家，精通系统性能分析和优化。',
        'prompt_up': '请为以下系统性能瓶颈设计优化方案：\n瓶颈描述：{bottleneck_description}\n系统架构：{system_architecture}\n优化目标：{optimization_targets}',
        'example_text': "```java\n// 缓存策略示例：多级缓存\npublic class MultiLevelCache<K, V> {\n    private final Cache<K, V> l1Cache;  // Caffeine（本地缓存）\n    private final Cache<K, V> l2Cache;  // Redis（分布式缓存）\n    \n    public V get(K key) {\n        // L1 缓存查询\n        V value = l1Cache.getIfPresent(key);\n        if (value != null) {\n            return value;\n        }\n        // L2 缓存查询\n        value = l2Cache.getIfPresent(key);\n        if (value != null) {\n            l1Cache.put(key, value);  // 回填 L1\n            return value;\n        }\n        // 数据库查询（缓存穿透防护）\n        value = loadFromDB(key);\n        if (value != null) {\n            l1Cache.put(key, value);\n            l2Cache.put(key, value);\n        } else {\n            // 缓存空值，防止缓存穿透\n            l1Cache.put(key, nullValue);\n            l2Cache.put(key, nullValue, 30_000);  // 短过期\n        }\n        return value;\n    }\n}\n```",
        'example_ext': 'java',
    },
    'performance/doc-4/': {
        'title': '容量规划',
        'overview': '容量规划确保系统有足够的资源支撑业务增长和峰值流量。本规范定义了容量评估、预测建模和扩容决策的标准流程。',
        'principles': ['数据驱动：基于历史数据和业务增长预测进行规划', '预留缓冲：容量规划需保留 30-50% 的缓冲容量', '持续评估：容量规划不是一次性工作，需持续评估调整', '自动化扩容：核心系统优先实现自动扩容'],
        'rules': [
            ('PERF-CAP-001', '容量规划每季度执行一次，覆盖核心业务系统', 'P0', '是'),
            ('PERF-CAP-002', '容量规划必须基于：当前使用率、历史增长趋势、业务增长预期', 'P0', '是'),
            ('PERF-CAP-003', '资源使用率超过 70% 时需启动扩容评估', 'P0', '是'),
            ('PERF-CAP-004', '关键业务系统必须配置自动扩容策略', 'P1', '推荐'),
            ('PERF-CAP-005', '每年至少进行一次全系统压力测试验证容量上限', 'P1', '推荐'),
        ],
        'checks': [
            '当前资源使用率已评估',
            '业务增长预期已确认',
            '容量预测已完成',
            '扩容预算已申请',
            '自动扩容已配置',
            '压力测试已安排',
        ],
        'prompt_sp': '你是一个容量规划专家，精通资源评估和扩容策略。',
        'prompt_up': '请为以下系统进行容量规划：\n系统名称：{system_name}\n当前负载：{current_load}\n业务增长预期：{growth_expectations}',
        'example_text': "```yaml\n# 容量规划报告\ncapacity_plan:\n  system: 订单服务\n  period: 2026 Q3\n  \n  current_usage:\n    cpu: 45%\n    memory: 62%\n    disk: 55%\n    peak_tps: 850/s\n  \n  growth_prediction:\n    business_growth: 30%（下半年促销活动）\n    predicted_peak_tps: 1200/s\n    required_capacity: 1800/s（50% 缓冲）\n  \n  recommendation:\n    - resource: 应用服务器\n      current: 4C8G × 3 实例\n      recommended: 4C8G × 5 实例\n      reason: 预计峰值 TPS 增长 41%\n    - resource: 数据库\n      current: 4C16G × 1\n      recommended: 8C32G × 2（主从）\n      reason: 写负载增加 + 高可用需求\n```",
        'example_ext': 'yaml',
    },
    'performance/doc-5/': {
        'title': '负载测试标准',
        'overview': '负载测试评估系统在预期和超出预期的负载下的行为和性能。本规范定义了负载测试的类型、场景设计、执行方法和结果分析标准。',
        'principles': ['场景贴近实际：测试场景基于真实用户行为模式', '分阶段施压：逐步增加负载找到系统拐点', '监控完备：测试期间全链路监控', '安全可控：测试不影响生产环境'],
        'rules': [
            ('PERF-LOAD-001', '每次重大版本发布前必须完成负载测试', 'P0', '是'),
            ('PERF-LOAD-002', '负载测试必须包含：基准测试、负载测试、压力测试、耐久测试', 'P0', '是'),
            ('PERF-LOAD-003', '测试负载模型必须基于生产环境的真实流量数据', 'P0', '是'),
            ('PERF-LOAD-004', '测试期间必须监控：响应时间、吞吐量、错误率、资源使用率', 'P0', '是'),
            ('PERF-LOAD-005', '测试结果必须包含：系统瓶颈点、最大安全吞吐量、建议限流阈值', 'P0', '是'),
        ],
        'checks': [
            '测试场景已设计',
            '负载模型已准备',
            '监控已配置',
            '安全措施已落实',
            '测试已执行',
            '报告已生成',
        ],
        'prompt_sp': '你是一个性能测试专家，精通 JMeter/Gatling/k6 等负载测试工具。',
        'prompt_up': '请为以下系统设计负载测试方案：\n系统名称：{system_name}\n峰值流量预期：{expected_peak_load}\n关键场景：{critical_scenarios}',
        'example_text': "```yaml\n# 负载测试方案\nload_test:\n  tool: k6\n  target: 订单服务 (staging)\n  \n  scenarios:\n    # 基准测试\n    - type: baseline\n      target_rate: 100 req/s\n      duration: 5min\n      \n    # 负载测试\n    - type: load\n      target_rate: 500 req/s\n      duration: 30min\n      \n    # 压力测试\n    - type: stress\n      start_rate: 100 req/s\n      end_rate: 2000 req/s\n      ramp_up: 10min\n      \n    # 耐久测试\n    - type: endurance\n      target_rate: 300 req/s\n      duration: 4h\n  \n  thresholds:\n    - metric: http_req_duration_p99\n      threshold: '<= 2000ms'\n    - metric: http_req_failed\n      threshold: '<= 0.01'\n```",
        'example_ext': 'yaml',
    },
}

SECURITY_CONTENT = {
    'security/doc-2/': {
        'title': '认证与授权规范',
        'overview': '认证与授权是系统安全的第一道屏障。本规范定义了用户认证、访问控制、权限模型和会话管理的安全标准。',
        'principles': ['最小权限：用户和系统只获得完成任务所需的最小权限', '纵深防御：多层次的认证和授权机制', '标准化协议：使用行业标准的认证协议', '审计完整：所有认证和授权事件必须记录审计日志'],
        'rules': [
            ('SEC-AUTH-001', '用户密码必须使用 bcrypt/Argon2 等慢哈希算法存储', 'P0', '是'),
            ('SEC-AUTH-002', 'API 认证必须使用 JWT/OAuth 2.0 等标准协议', 'P0', '是'),
            ('SEC-AUTH-003', '所有 API 请求必须经过身份验证（除公开接口）', 'P0', '是'),
            ('SEC-AUTH-004', '账户登录失败 5 次后必须临时锁定（至少 15 分钟）', 'P0', '是'),
            ('SEC-AUTH-005', '未操作 30 分钟后会话必须过期', 'P0', '是'),
            ('SEC-AUTH-006', '权限模型采用 RBAC（基于角色的访问控制）', 'P1', '推荐'),
        ],
        'checks': [
            '密码哈希算法合规',
            '认证协议标准',
            'API 鉴权全覆盖',
            '登录失败锁定机制',
            '会话过期时间设置',
            'RBAC 模型已实现',
        ],
        'prompt_sp': '你是一个安全架构师，精通认证授权体系和零信任架构。',
        'prompt_up': '请为以下系统设计认证授权方案：\n系统类型：{system_type}\n用户角色：{user_roles}\n安全要求：{security_requirements}',
        'example_text': "```python\n# JWT 认证示例\nimport jwt\nfrom datetime import datetime, timedelta\n\nclass AuthService:\n    SECRET_KEY = os.environ['JWT_SECRET']\n    ACCESS_TOKEN_EXPIRE = timedelta(hours=2)\n    REFRESH_TOKEN_EXPIRE = timedelta(days=7)\n    \n    def create_tokens(self, user_id: str, roles: list[str]) -> dict:\n        now = datetime.utcnow()\n        access_payload = {\n            'sub': user_id,\n            'roles': roles,\n            'type': 'access',\n            'iat': now,\n            'exp': now + self.ACCESS_TOKEN_EXPIRE\n        }\n        refresh_payload = {\n            'sub': user_id,\n            'type': 'refresh',\n            'iat': now,\n            'exp': now + self.REFRESH_TOKEN_EXPIRE\n        }\n        return {\n            'access_token': jwt.encode(access_payload, self.SECRET_KEY, algorithm='HS256'),\n            'refresh_token': jwt.encode(refresh_payload, self.SECRET_KEY, algorithm='HS256')\n        }\n    \n    def verify_token(self, token: str) -> dict:\n        try:\n            payload = jwt.decode(token, self.SECRET_KEY, algorithms=['HS256'])\n            return payload\n        except jwt.ExpiredSignatureError:\n            raise AuthException('Token 已过期')\n        except jwt.InvalidTokenError:\n            raise AuthException('无效的 Token')\n```",
        'example_ext': 'py',
    },
    'security/doc-3/': {
        'title': '数据加密方案',
        'overview': '数据加密保护数据的机密性和完整性，防止未授权的数据访问和泄露。本规范定义了不同场景下的加密策略和密钥管理要求。',
        'principles': ['分类分级：数据按敏感度使用不同加密策略', '传输加密：所有网络通信使用 TLS', '存储加密：敏感数据在存储层加密', '端到端保护：数据全生命周期加密'],
        'rules': [
            ('SEC-CRYPTO-001', '传输中的数据必须使用 TLS 1.2+ 加密', 'P0', '是'),
            ('SEC-CRYPTO-002', '存储的敏感数据（PII/金融数据）必须使用 AES-256 加密', 'P0', '是'),
            ('SEC-CRYPTO-003', '密钥必须使用 KMS（密钥管理服务）管理，禁止硬编码在代码中', 'P0', '是'),
            ('SEC-CRYPTO-004', '加密密钥必须定期轮换（建议 90 天轮换一次）', 'P0', '是'),
            ('SEC-CRYPTO-005', '数据库敏感字段必须使用列级加密', 'P1', '推荐'),
        ],
        'checks': [
            'TLS 版本合规',
            '存储加密已实施',
            '密钥管理已使用 KMS',
            '密钥轮换已配置',
            '列级加密已实施',
            '加密算法合规',
        ],
        'prompt_sp': '你是一个密码学安全专家，精通数据加密和安全架构。',
        'prompt_up': '请为以下数据设计加密方案：\n数据类型：{data_types}\n合规要求：{compliance_requirements}\n系统架构：{system_architecture}',
        'example_text': "```yaml\n# 数据加密方案\nencryption:\n  # 传输加密\n  transit:\n    protocol: TLS 1.3\n    scope: 所有外网通信\n    cert_manager: Let's Encrypt / cert-manager\n    \n  # 存储加密\n  at_rest:\n    - layer: 磁盘\n      method: AES-256-XTS\n      scope: 全部数据盘\n      key_source: Cloud KMS\n    - layer: 数据库\n      method: AES-256-GCM\n      scope: 用户表敏感字段（手机号、身份证、银行卡）\n      key_rotation: 90 天\n    \n  # 应用层加密\n  application:\n    - method: AES-256-GCM\n      scope: 个人敏感信息\n      key_source: KMS + DEK 缓存\n      key_rotation: 每次读取时\n```",
        'example_ext': 'yaml',
    },
    'security/doc-4/': {
        'title': '密钥管理规范',
        'overview': '密钥管理是数据加密体系的核心保障。本规范覆盖了密钥的生命周期管理、存储安全、轮换策略和访问控制。',
        'principles': ['集中管理：所有密钥通过 KMS 集中管理', '分级保护：密钥按使用场景和敏感度分级', '安全存储：密钥的存储和使用必须安全隔离', '审计追踪：所有密钥操作必须记录日志'],
        'rules': [
            ('SEC-KM-001', '所有密钥必须通过 KMS（云 KMS/HashiCorp Vault）管理', 'P0', '是'),
            ('SEC-KM-002', '密钥禁止以明文形式存储在代码库、配置文件或环境变量中', 'P0', '是'),
            ('SEC-KM-003', '生产环境密钥与开发/测试环境密钥必须完全隔离', 'P0', '是'),
            ('SEC-KM-004', '密钥访问必须有审计日志记录：谁、何时、为何、访问了哪个密钥', 'P0', '是'),
            ('SEC-KM-005', '密钥轮换周期：加密密钥 90 天、签名密钥 180 天、CA 密钥 365 天', 'P0', '是'),
        ],
        'checks': [
            'KMS 已部署',
            '密钥分级已完成',
            '生产/测试密钥已隔离',
            '访问审计已开启',
            '轮换周期已配置',
            '灾备方案已准备',
        ],
        'prompt_sp': '你是一个密钥管理专家，精通 KMS 和安全架构。',
        'prompt_up': '请为以下系统设计密钥管理方案：\n系统架构：{system_architecture}\n密钥类型：{key_types}\n合规要求：{compliance_requirements}',
        'example_text': "```hcl\n# HashiCorp Vault 策略示例\n# 密钥管理策略\npath \"secret/data/production/*\" {\n  capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\"]\n  required_parameters = [\"data\"]\n  \n  # 生产环境密钥仅允许运维团队写入\n  constraint {\n    path \"secret/data/production/db/*\" {\n      capabilities = [\"read\"]\n    }\n    path \"secret/data/production/api/*\" {\n      capabilities = [\"read\"]\n    }\n  }\n}\n\n# 密钥轮换配置\npath \"sys/rotate\" {\n  capabilities = [\"sudo\"]\n}\n\n# 审计日志\npath \"audit/*\" {\n  capabilities = [\"read\", \"list\"]\n}\n```",
        'example_ext': 'hcl',
    },
    'security/doc-5/': {
        'title': '安全审计规范',
        'overview': '安全审计定期检查系统的安全状态，发现安全漏洞和配置偏差。本规范定义了安全审计的周期、范围和整改流程。',
        'principles': ['定期审计：按固定周期执行安全审计', '全面覆盖：覆盖基础设施、应用、数据和流程', '独立客观：审计由独立于被审计方的人员执行', '闭环管理：发现问题到整改完成全程跟踪'],
        'rules': [
            ('SEC-AUD-001', '安全审计至少每季度执行一次', 'P0', '是'),
            ('SEC-AUD-002', '审计范围必须覆盖：基础设施安全、应用安全、数据安全、权限安全', 'P0', '是'),
            ('SEC-AUD-003', '发现的安全漏洞必须在修复时限内完成修复', 'P0', '是'),
            ('SEC-AUD-004', '高危漏洞修复时限为 7 天，中危 30 天，低危 90 天', 'P0', '是'),
            ('SEC-AUD-005', '审计报告必须提交安全委员会并归档', 'P0', '是'),
        ],
        'checks': [
            '审计计划已制定',
            '审计范围已确认',
            '审计已执行',
            '漏洞已登记',
            '修复时限已配置',
            '审计报告已归档',
        ],
        'prompt_sp': '你是一个安全审计专家，精通安全评估和合规审计。',
        'prompt_up': '请为以下系统制定安全审计计划：\n系统名称：{system_name}\n合规要求：{compliance_requirements}\n上次审计结果：{last_audit_results}',
        'example_text': "```yaml\n# 安全审计清单\naudit_checklist:\n  infrastructure:\n    - item: 操作系统补丁更新\n      check: 所有服务器是否已更新最新安全补丁\n      method: 自动化扫描\n    - item: 防火墙规则\n      check: 最小化开放端口\n      method: 规则审查\n      \n  application:\n    - item: 依赖漏洞扫描\n      check: 所有依赖无已知 CVE\n      method: SCA 工具（Trivy/Snyk）\n    - item: 代码安全审查\n      check: 关键模块完成安全代码审查\n      method: Code Review\n  \n  data:\n    - item: 敏感数据发现\n      check: 数据库和文件系统中的敏感数据\n      method: 数据扫描\n```",
        'example_ext': 'yaml',
    },
    'security/doc-6/': {
        'title': '安全漏洞管理',
        'overview': '安全漏洞管理建立漏洞发现、评估、修复和验证的闭环流程，确保系统的安全漏洞得到及时有效的处理。',
        'principles': ['全面发现：多种渠道发现安全漏洞', '风险评估：按 CVSS 评分确定修复优先级', '及时修复：按风险等级设置修复 SLA', '验证闭环：修复完成后必须验证有效性'],
        'rules': [
            ('SEC-VULN-001', '漏洞来源包括：SAST 扫描、SCA 扫描、DAST 扫描、渗透测试、安全公告', 'P0', '是'),
            ('SEC-VULN-002', '漏洞按 CVSS 评分分级：高危（>= 7.0）、中危（4.0-6.9）、低危（< 4.0）', 'P0', '是'),
            ('SEC-VULN-003', '高危漏洞 7 天内修复，中危 30 天，低危 90 天', 'P0', '是'),
            ('SEC-VULN-004', '修复完成后必须重新扫描验证漏洞已修复', 'P0', '是'),
            ('SEC-VULN-005', '漏洞扫描工具每周至少执行一次全量扫描', 'P1', '推荐'),
        ],
        'checks': [
            '漏洞扫描已定期执行',
            '漏洞评估已分级',
            '修复时限已定义',
            '修复验证已实施',
            '漏洞报告已同步',
            '漏洞趋势已跟踪',
        ],
        'prompt_sp': '你是一个安全工程师，精通漏洞管理和安全运营。',
        'prompt_up': '请为以下漏洞制定修复方案：\n漏洞描述：{vulnerability_description}\n影响系统：{affected_systems}\n风险等级：{risk_level}',
        'example_text': "```yaml\n# 漏洞管理记录\nvulnerability:\n  id: VULN-2026-001\n  title: Apache Log4j 远程代码执行（CVE-2021-44228）\n  source: SCA 扫描（Trivy）\n  severity: 高危（CVSS 10.0）\n  \n  affected_systems:\n    - service: 用户服务\n      version: v2.3.1\n      library: log4j-core 2.14.0\n    - service: 订单服务\n      version: v3.1.0\n      library: log4j-api 2.14.0\n  \n  remediation:\n    fix: 升级 log4j 至 2.17.1+\n    workaround: 设置 log4j2.formatMsgNoLookups=true\n    verification: Trivy 重新扫描验证\n    deadline: 2026-07-05（7 天内）\n  \n  status: 修复中\n  assignee: 安全组\n```",
        'example_ext': 'yaml',
    },
    'security/owasp-top/': {
        'title': 'OWASP Top 10 防护',
        'overview': 'OWASP Top 10 是 Web 应用程序最常见的安全风险列表。本规范提供了针对每个风险的防护措施和验证方法。',
        'principles': ['主动防御：在开发阶段预防安全风险', '纵深防御：多层安全防护机制', '持续验证：自动化安全扫描集成到 CI/CD', '安全意识：培养开发团队的安全编码意识'],
        'rules': [
            ('SEC-OWASP-001', '所有 Web 应用必须实施 OWASP Top 10 防护措施', 'P0', '是'),
            ('SEC-OWASP-002', '用户输入必须经过严格的输入验证和输出编码', 'P0', '是'),
            ('SEC-OWASP-003', '所有 API 必须实施速率限制和请求大小限制', 'P0', '是'),
            ('SEC-OWASP-004', '安全头部（CSP、X-Frame-Options、HSTS 等）必须正确配置', 'P0', '是'),
            ('SEC-OWASP-005', 'CI/CD 流水线中必须集成 SAST 和 SCA 安全扫描', 'P0', '是'),
        ],
        'checks': [
            'SAST 扫描已集成',
            'SCA 扫描已集成',
            '安全头部已配置',
            '输入验证已实施',
            '速率限制已配置',
            '安全编码培训已完成',
        ],
        'prompt_sp': '你是一个 Web 安全专家，精通 OWASP 安全标准和防护技术。',
        'prompt_up': '请为以下 Web 应用设计 OWASP 防护方案：\n应用类型：{app_type}\n技术栈：{tech_stack}\n合规要求：{compliance_requirements}',
        'example_text': "```yaml\n# OWASP Top 10 防护措施\nprotections:\n  A01:\n    name: 访问控制失效（Broken Access Control）\n    prevention:\n      - 默认拒绝访问策略\n      - RBAC 权限模型\n      - API 级别权限校验\n      - 禁用目录列表\n      \n  A03:\n    name: 注入（Injection）\n    prevention:\n      - 参数化查询（PreparedStatement）\n      - 输入验证白名单\n      - 输出 HTML 编码\n      - ORM 框架使用\n      \n  A05:\n    name: 安全配置错误（Security Misconfiguration）\n    prevention:\n      - 安全头部配置：\n        Content-Security-Policy: default-src 'self'\n        X-Frame-Options: DENY\n        Strict-Transport-Security: max-age=31536000\n        X-Content-Type-Options: nosniff\n      - 最小化开放端口\n      - 禁用默认账户\n```",
        'example_ext': 'yaml',
    },
}

WORKFLOW_CONTENT = {
    'workflow/doc-1/': {
        'title': '状态机模式',
        'overview': '状态机（State Machine）是管理业务对象状态变更的标准模式，确保状态转换符合业务规则。本规范定义了状态机的设计标准和实现规范。',
        'principles': ['有限状态：状态集合预先定义且有限', '合法转换：状态转换必须经过显式定义', '单一事件驱动：每个状态转换由特定事件触发', '可追踪：状态变更历史必须完整记录'],
        'rules': [
            ('WF-SM-001', '所有状态机必须显式定义：状态集、事件集、转换规则、初始状态、终态', 'P0', '是'),
            ('WF-SM-002', '非法状态转换必须被框架拒绝并抛出明确异常', 'P0', '是'),
            ('WF-SM-003', '状态转换前后可以有 Action（前处理/后处理）', 'P0', '是'),
            ('WF-SM-004', '状态机的定义必须集中管理，禁止分散在多个文件中', 'P0', '是'),
            ('WF-SM-005', '关键业务对象的状态变更必须发布领域事件', 'P1', '推荐'),
        ],
        'checks': [
            '状态集合已定义',
            '转换规则已定义',
            '初始/结束状态已指定',
            '非法转换已拦截',
            '转换事件已发布',
            '状态机文档已更新',
        ],
        'prompt_sp': '你是一个工作流架构专家，精通状态机和工作流引擎设计。',
        'prompt_up': '请为以下业务对象设计状态机：\n业务对象：{business_object}\n业务场景：{business_scenario}\n状态需求：{state_requirements}',
        'example_text': "```java\n// 状态机示例：订单状态机\npublic enum OrderState implements State {\n    DRAFT, PENDING_PAYMENT, PAID, PROCESSING, SHIPPED, DELIVERED, COMPLETED, CANCELLED, REFUNDED;\n}\n\npublic enum OrderEvent implements Event {\n    SUBMIT, PAY, PROCESS, SHIP, DELIVER, COMPLETE, CANCEL, REFUND, TIMEOUT;\n}\n\n// 状态转换规则\npublic class OrderStateMachine {\n    private StateMachine<OrderState, OrderEvent> machine;\n    \n    public OrderStateMachine() {\n        machine = StateMachineBuilder.<OrderState, OrderEvent>builder()\n            .initialState(OrderState.DRAFT)\n            // 基本流程\n            .transition(DRAFT, SUBMIT, PENDING_PAYMENT)\n            .transition(PENDING_PAYMENT, PAY, PAID)\n            .transition(PAID, PROCESS, PROCESSING)\n            .transition(PROCESSING, SHIP, SHIPPED)\n            .transition(SHIPPED, DELIVER, DELIVERED)\n            .transition(DELIVERED, COMPLETE, COMPLETED)\n            // 取消流程\n            .transition(DRAFT, CANCEL, CANCELLED)\n            .transition(PENDING_PAYMENT, CANCEL, CANCELLED)\n            .transition(PAID, REFUND, REFUNDED)\n            // 超时处理\n            .transition(PENDING_PAYMENT, TIMEOUT, CANCELLED)\n            // 前置校验\n            .before(PAY, this::validatePayment)\n            .after(PAY, this::notifyPaymentReceived)\n            .build();\n    }\n}\n```",
        'example_ext': 'java',
    },
    'workflow/doc-2/': {
        'title': '工作流引擎',
        'overview': '工作流引擎管理和执行业务流程的自动化。本规范定义了工作流的建模标准、引擎选型和集成方式。',
        'principles': ['可视化建模：优先使用 BPMN 等可视化标准进行流程建模', '可监控：工作流执行状态需实时可查询', '可干预：支持人工干预（驳回/转办/终止）', '可审计：所有流程实例的执行历史完整记录'],
        'rules': [
            ('WF-ENG-001', '工作流定义必须使用 BPMN 2.0 标准建模', 'P0', '是'),
            ('WF-ENG-002', '工作流引擎必须支持：用户任务、服务任务、网关（排他/并行/包容）、子流程', 'P0', '是'),
            ('WF-ENG-003', '流程实例状态必须包括：运行中、挂起、已完成、已终止', 'P0', '是'),
            ('WF-ENG-004', '超时未处理的用户任务必须发送催办通知', 'P0', '是'),
            ('WF-ENG-005', '工作流引擎必须提供 REST API 进行流程操作', 'P1', '推荐'),
        ],
        'checks': [
            'BPMN 模型已创建',
            '工作流引擎已部署',
            '流程节点已定义',
            '超时催办已配置',
            '执行监控已就绪',
            '流程历史已记录',
        ],
        'prompt_sp': '你是一个工作流架构专家，精通 BPMN 和工作流引擎。',
        'prompt_up': '请为以下业务流程设计工作流：\n流程名称：{process_name}\n参与角色：{participant_roles}\n业务规则：{business_rules}',
        'example_text': "```xml\n<!-- BPMN 2.0 流程定义示例：订单审批流程 -->\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<bpmn:definitions xmlns:bpmn=\"http://www.omg.org/spec/BPMN/20100524/MODEL\">\n  <bpmn:process id=\"order_approval\" name=\"订单审批流程\" isExecutable=\"true\">\n    <bpmn:startEvent id=\"start\" name=\"订单提交\">\n      <bpmn:outgoing>flow_start</bpmn:outgoing>\n    </bpmn:startEvent>\n    \n    <!-- 自动验证任务 -->\n    <bpmn:serviceTask id=\"validate\" name=\"订单验证\" implementation=\"validateOrderService\">\n      <bpmn:incoming>flow_start</bpmn:incoming>\n      <bpmn:outgoing>flow_validate</bpmn:outgoing>\n    </bpmn:serviceTask>\n    \n    <!-- 排他网关：金额判断 -->\n    <bpmn:exclusiveGateway id=\"amount_gateway\" name=\"金额判断\">\n      <bpmn:incoming>flow_validate</bpmn:incoming>\n      <bpmn:outgoing>flow_auto</bpmn:outgoing>\n      <bpmn:outgoing>flow_manual</bpmn:outgoing>\n    </bpmn:exclusiveGateway>\n    \n    <!-- 条件：小于 10000 自动通过 -->\n    <bpmn:sequenceFlow id=\"flow_auto\" sourceRef=\"amount_gateway\" targetRef=\"auto_approve\">\n      <bpmn:conditionExpression xsi:type=\"tFormalExpression\">${amount < 10000}</bpmn:conditionExpression>\n    </bpmn:sequenceFlow>\n    \n    <!-- 人工审批 -->\n    <bpmn:userTask id=\"approval\" name=\"经理审批\">\n      <bpmn:incoming>flow_manual</bpmn:incoming>\n      <bpmn:outgoing>flow_approval</bpmn:outgoing>\n    </bpmn:userTask>\n  </bpmn:process>\n</bpmn:definitions>\n```",
        'example_ext': 'xml',
    },
    'workflow/bpmn/': {
        'title': 'BPMN 标准实践',
        'overview': 'BPMN（业务流程模型和符号）是业务流程建模的国际标准。本规范提供了 BPMN 建模的最佳实践、符号使用指南和模型质量标准。',
        'principles': ['标准化符号：遵循 BPMN 2.0 符号规范', '层次化建模：按流程层次逐级细化', '可执行优先：模型需具备可执行性', '清晰简洁：避免过度复杂的模型设计'],
        'rules': [
            ('WF-BPMN-001', 'BPMN 模型必须遵循 BPMN 2.0 规范，使用标准符号', 'P0', '是'),
            ('WF-BPMN-002', '流程模型按三级分层：流程域 → 端到端流程 → 子流程', 'P0', '是'),
            ('WF-BPMN-003', '泳道（Lane）按角色/部门划分，清晰展示职责分工', 'P0', '是'),
            ('WF-BPMN-004', '排他网关必须有默认分支，避免流程卡死', 'P0', '是'),
            ('WF-BPMN-005', '消息流用于跨组织/跨系统通信，与顺序流区分', 'P1', '推荐'),
        ],
        'checks': [
            '符号使用规范',
            '流程层次清晰',
            '泳道划分合理',
            '网关分支完整',
            '消息流正确使用',
            '模型可执行验证',
        ],
        'prompt_sp': '你是一个 BPMN 专家，精通业务流程建模和流程优化。',
        'prompt_up': '请使用 BPMN 为以下流程建模：\n流程名称：{process_name}\n流程描述：{process_description}\n参与角色：{participant_roles}',
        'example_text': "```yaml\n# BPMN 流程模型定义（使用 Camunda 格式）\nprocess:\n  id: order-to-cash\n  name: 从订单到收款\n  version: 2.0\n  \n  participants:\n    - name: 客户\n      type: external\n    - name: 销售部\n      type: lane\n    - name: 仓库\n      type: lane\n    - name: 财务部\n      type: lane\n  \n  elements:\n    # 开始事件\n    - id: start\n      type: startEvent\n      name: 客户下单\n      lane: 客户\n    \n    # 服务任务（系统自动处理）\n    - id: validate\n      type: serviceTask\n      name: 订单验证\n      lane: 销售部\n      implementation: OrderValidationService\n    \n    # 排他网关\n    - id: gateway\n      type: exclusiveGateway\n      name: 金额判断\n      outgoing:\n        - condition: 金额 <= 10000\n          target: auto_approve\n        - condition: 金额 > 10000\n          target: manager_review\n        - default: auto_approve\n```",
        'example_ext': 'yaml',
    },
    'workflow/saga/': {
        'title': 'Saga 分布式事务',
        'overview': 'Saga 是管理跨服务分布式事务的经典模式，通过补偿机制保障数据的最终一致性。本规范定义了 Saga 的设计原则、编排方式和失败处理。',
        'principles': ['最终一致性：Saga 不保证实时一致性，最终达到一致', '补偿机制：每个步骤必须有对应的补偿操作', '幂等性：所有操作和补偿操作必须支持幂等', '可恢复：失败时可以从中断点恢复继续或回滚'],
        'rules': [
            ('WF-SAGA-001', 'Saga 中的每一步必须有对应的补偿操作（Compensation）', 'P0', '是'),
            ('WF-SAGA-002', 'Saga 执行必须记录执行状态和执行历史', 'P0', '是'),
            ('WF-SAGA-003', 'Saga 失败后必须执行完整的补偿流程（逆向回滚）', 'P0', '是'),
            ('WF-SAGA-004', 'Saga 编排推荐使用编排模式（Orchestration）而非舞蹈模式（Choreography）', 'P0', '是'),
            ('WF-SAGA-005', 'Saga 协调器必须做好容错和幂等处理', 'P1', '推荐'),
        ],
        'checks': [
            '补偿操作已定义',
            '幂等性已实现',
            '执行状态已记录',
            '失败恢复流程已设计',
            '协调器已部署',
            '超时处理已配置',
        ],
        'prompt_sp': '你是一个分布式系统专家，精通 Saga 模式和分布式事务。',
        'prompt_up': '请为以下业务场景设计 Saga 分布式事务方案：\n业务流程：{business_process}\n涉及服务：{involved_services}\n一致性要求：{consistency_requirements}',
        'example_text': "```java\n// Saga 编排示例：下单流程\n@Component\npublic class CreateOrderSaga implements Saga<CreateOrderRequest> {\n    \n    @Override\n    public void define(SagaDefinition<CreateOrderRequest> saga) {\n        saga.step(\"reserveInventory\")\n            .invoke(inventoryService::reserve)  // 正向操作\n            .withCompensation(inventoryService::release)  // 补偿操作\n            .onReply(InventoryReserved.class, this::onInventoryReserved)\n            .onError(this::onInventoryError);\n        \n        saga.step(\"processPayment\")\n            .invoke(paymentService::charge)\n            .withCompensation(paymentService::refund)\n            .onReply(PaymentProcessed.class, this::onPaymentProcessed);\n        \n        saga.step(\"prepareShipping\")\n            .invoke(shippingService::prepare)\n            .withCompensation(shippingService::cancel)\n            .onReply(ShippingPrepared.class, this::onShippingPrepared);\n    }\n    \n    @SagaEventHandler(associativeWith = \"reserveInventory\")\n    public void onInventoryReserved(InventoryReserved event, SagaState state) {\n        log.info(\"库存预留成功\");\n    }\n    \n    public void onInventoryError(Throwable error, SagaState state) {\n        log.error(\"库存预留失败，开始补偿流程\");\n        // Saga 框架自动执行已通过步骤的补偿操作\n    }\n}\n```",
        'example_ext': 'java',
    },
}

# ── Combine all domains ──
ALL_NEW = {}
for d in [ANALYTICS, CAPABILITY, COMPLIANCE, DOMAIN_CONTENT, EVENT_CONTENT, 
          OPERATION_CONTENT, PERFORMANCE_CONTENT, SECURITY_CONTENT, WORKFLOW_CONTENT]:
    ALL_NEW.update(d)

if __name__ == "__main__":
    print(f"Generated {len(ALL_NEW)} topics across 9 domains")
    for k in sorted(ALL_NEW.keys()):
        print(f"  {k} -> {ALL_NEW[k]['title']}")
